### ISSUE TITLE
Missing export when importing mpl-token-metadata

### ISSUE THREAD

**Issue by mwilc0x** [metaplex-foundation/js#121]
Hi Metaplex team,

Am seeing a missing export when importing in a deno build:

`
error: Uncaught SyntaxError: The requested module '/v84/@metaplex-foundation/mpl-token-metadata@2.1.2/deno/mpl-token-metadata.js' does not provide an export named 'Edition'
    at <anonymous> (https://esm.sh/v84/@metaplex-foundation/js-next@0.9.0/deno/js-next.js:8:67021)
`

Searching for the import:
https://github.com/metaplex-foundation/js-next/search?q=Edition

Searching for the export:
https://github.com/metaplex-foundation/metaplex-program-library/search?q=Edition+path%3Atoken-metadata%2F+extension%3Ats

Am not sure if correct would be to remove the imports here.

**Comment by mwilc0x** [comment]
I might be importing it wrong. I am using the [importMap](https://deno.land/manual/linking_to_external_code/import_maps) feature of deno:

`"@metaplex-foundation/js-next": "https://esm.sh/@metaplex-foundation/js-next"`

**Comment by lorisleiva** [comment]
I've never used esm.sh before so I can't help there I'm afraid. 😕

**Comment by lorisleiva** [comment]
Hi there 👋 Just closing this for now since the export is available in the MPL library. Feel free to open a new issue with updated information if you need to. Thank you. 🌹
