### ISSUE TITLE
Metadata load example not working

### ISSUE THREAD

**Issue by AWolf81** [metaplex-foundation/js#129]
**Describe the bug**
As mentioned in #41 there is a change in the exports so the first example in [getting-started](https://docs.metaplex.com/sdk/js/getting-started) is not working with v4.10.1.

**To Reproduce**
Try the example code with the version of Metaplex [v4.10.1](https://unpkg.com/@metaplex/js@4.10.1/lib/index.cjs.js).
```js
import { Connection, programs } from '@metaplex/js';

const connection = new Connection('devnet');
const tokenPublicKey = 'Gz3vYbpsB2agTsAwedtvtTkQ1CG9vsioqLW3r9ecNpvZ';

const run = async () => {
  try {
    const ownedMetadata = await programs.metadata.Metadata.load(connection, tokenPublicKey); // <<<<< line in question!
    console.log(ownedMetadata);
  } catch {
    console.log('Failed to fetch metadata');
  }
};

run();
```

**Expected behavior**
The docs should be clear on what to import and how to load the Metadata.
If the code below is OK, I could update the docs.

To avoid the confusion in the future, it would be good to have a version indication in the docs but that should be tracked in a separate issue (e.g. add a version dropdown like in the [Atlassian docs](https://confluence.atlassian.com/bitbucketserver), see top right dropdown)

**Working code with v4.10.1**
```ts
import { Connection } from "@metaplex/js";
import { Metadata } from "@metaplex-foundation/mpl-token-metadata";

const connection = new Connection("devnet");
const tokenPublicKey = "Gz3vYbpsB2agTsAwedtvtTkQ1CG9vsioqLW3r9ecNpvZ";
const run = async () => {
  try {
    const ownedMetadata = await Metadata.load(connection, tokenPublicKey);
    console.log(ownedMetadata);
  } catch (ex) {
    console.log("Failed to fetch metadata", ex);
  }
};

run();
```
**Additional context**
Codesandbox for the above code can be found [here](https://codesandbox.io/s/metaplex-query-example-lib-v4-10-1-1bmjg)

[Codesandbox with metaplex/js v4.1.0](https://codesandbox.io/s/metaplex-query-example-lib-v4-1-0-7wbfu)

**Comment by aheckmann** [comment]
Thanks for the bug report. Fixed in 4.11.3
