### ISSUE TITLE
Uninitialized Wallet Adapter

### ISSUE THREAD

**Issue by Steenos** [metaplex-foundation/js#133]
I get this error following along with the documentation example
<img width="336" alt="Screen Shot 2022-06-14 at 5 51 33 PM" src="https://user-images.githubusercontent.com/13594989/173695827-c0c32d39-c42d-4ec3-8c02-faa50547485e.png">

**Comment by Steenos** [comment]
Hey! thanks for your help, heres the repo:  https://github.com/Steenos/metaplex-playground

**Comment by lorisleiva** [comment]
The problem lies here: https://github.com/Steenos/metaplex-playground/blob/main/pages/index.tsx#L8

You've got to give the entire Wallet store for it to work.

```diff
- const { wallet, publicKey } = useWallet();
+ const wallet = useWallet();
+ const { publicKey } = wallet;

  ...
  mx.use(walletAdapterIdentity(wallet));
```
