### ISSUE TITLE
Please add Auction, WhiteListedCreator and InitStore

### ISSUE THREAD

**Issue by mrdhanz** [metaplex-foundation/js#135]
Hi metaplex developers. in SDK versions before this feature existed, after I migrated to the latest version this feature disappeared. will it be added to this sdk version? but in this latest version it is very easy to use to make NFT and more optimal in its performance. 
I hope this functionality is added to the latest version because I like the class structure in this SDK version
Thank you

**Comment by lorisleiva** [comment]
Hi there 👋 

This new SDK is a complete rewrite so we're not planning on re-adding exact classes. Instead, we're rethinking the way our users interact with our SDKs.

I am currently working on integrating the new SDK with the Auction House program but we have no plan to support the previous Auctions program whose feature set has been replaced by Auction House.

That being said, I would love to hear about your use cases with the previous JS SDK so I can focus on features that will help you migrate to the new SDK.

**Comment by lorisleiva** [comment]
Hi there 👋 

I'm going to close this due to inactivity but know that the Auction House module is well on its way and now needs documenting. We'll also try to allocate some time for some reference implementations so it's easy to understand how to set up your own marketplace.
