### ISSUE TITLE
Error when Calling uploadMetadata method()

### ISSUE THREAD

**Issue by MNaguib2611** [metaplex-foundation/js#138]
I am getting the below error whenever I try to use the uploadMetadata method() from my react project
i am using other methods like getNftByCreator ()  without any issues
------------
`Uncaught (in promise) TypeError: _bundlr_network_client__WEBPACK_IMPORTED_MODULE_0__ is not a constructor
at BundlrStorageDriver.initNodeBundlr (BundlrStorageDriver.ts:195:1)
at BundlrStorageDriver.initBundlr (BundlrStorageDriver.ts:175:1)
at BundlrStorageDriver.bundlr (BundlrStorageDriver.ts:162:1)
at BundlrStorageDriver.uploadAll (BundlrStorageDriver.ts:84:1)
at StorageClient.uploadAll (StorageClient.ts:45:1)
at Object.handle (uploadMetadata.ts:33:1)
at Task.callback (OperationClient.ts:66:1)
at Task.ts:82:1
at Disposable.run (Disposable.ts:34:1)
at Task.forceRun (Task.ts:74:1)`
------------------------
`
const fromWallet = Keypair.generate(); 
console.log(fromWallet);
const connection = new Connection(clusterApiUrl("devnet"));
const metaplex = Metaplex.make(connection)
 .use(keypairIdentity(fromWallet))
 .use(
   bundlrStorage({
     address: "https://devnet.bundlr.network",
     providerUrl: "https://api.devnet.solana.com",
     timeout: 60000,
   })
 );
`
 
`
 const { uri } = await metaplex.nfts().uploadMetadata({
        name: "My NFT",
        description: "My description",
        image: "https://arweave.net/rP-4r6VookQuSb8IjEep5bZgh6Z7c-MAW8uTkhtczOw",
    });
`
   

Someone else on stackoverflow have my same issue

[https://stackoverflow.com/questions/72626538/typeerror-bundlr-network-client-webpack-imported-module-0-is-not-a-construc](url)

**Comment by mrdhanz** [comment]
Keypair wallets only work on nodes, because you implement them on the web. You must use a wallet adapter. so, bundlr need confirmation signature for upload and verify transaction

**Comment by MNaguib2611** [comment]
> Keypair wallets only work on nodes, because you deploy them on the web. You must use a wallet adapter. so, bundlr need confirmation signature to upload and verify transaction

thank you for your response 
how can I use walletAdapter with the current connected phantom wallet ?

**Comment by lorisleiva** [comment]
Hey 👋 Whilst typically you'd use the wallet adapter in the browser, you should also be able to handle Keypairs there. I'll try to find time to investigate this issue as soon as I can. Thank you for your understanding. 🌺

**Comment by MNaguib2611** [comment]
After using the adapter from [https://github.com/solana-labs/wallet-adapter](url) I was finally able to use the uploadMetadata() and minted my first NFT through react app


I was not able to use the function by using the keypairIdentity, only walletAdapterIdentity worked for me 

Thank you @lorisleiva  @mrdhanz  for your help ,I really appreciate it

**Comment by lorisleiva** [comment]
Hi there 👋

I'm going to close this due to inactivity but feel free to open a new issue with updated information if you need to.

Thank you for your understanding.
