### ISSUE TITLE
Utility modules don't export in actions/index.ts

### ISSUE THREAD

**Issue by dtome123** [metaplex-foundation/js#145]
**Describe the bug**
Utility modules don't export

Desciption:
I try to call **createExternalPriceAccount** function but it can't found. I realize that all modules of utility folder are not exported in file index.ts (actions). So it is a bug ?

Thanks

**Comment by aheckmann** [comment]
Yep! Good catch. This was missed in https://github.com/metaplex-foundation/js/commit/715d1d4b98c64f3656b0d4a5dc6d0b77041171bf 

Will update today
