### ISSUE TITLE
Question about InitAuctionManagerV2

### ISSUE THREAD

**Issue by dtome123** [metaplex-foundation/js#148]
Sorry, I have a question. I saw code t in metaplex-foundation/metaplex/js/packages/web/actions and it use **"initAuctionManagerV2"** function in **createAuctionManager.ts**. But javascript JDK don't have it, and I used the "**InitAuctionManagerV2**" class to create auction manager. Then it failed because of **acceptPaymentAccount** parameter. So in the future,  will be **createAuctionManager** or **initAuctionManager** function added? 

Thanks

**Comment by aheckmann** [comment]
This project is not a 1-1 mapping of what is in the metaplex ui. However, this project will soon support all core functionality of our MPL rust programs. We are very actively working on code generation tools to fast forward this project. Stay tuned.
