### ISSUE TITLE
error only in findAllByOwner 'Assertion failed'

### ISSUE THREAD

**Issue by wfp2002** [metaplex-foundation/js#150]
node_modules/bn.js/lib/bn.js:6
    if (!val) throw new Error(msg || 'Assertion failed');

**Comment by wfp2002** [comment]
Error on Bn

**Comment by jensnowww** [comment]
Hi were you able to solved this issue?

**Comment by milorue** [comment]
I would also like to know how @wfp2002 you fixed it
