### ISSUE TITLE
Incompatibility with ES2020 BN

### ISSUE THREAD

**Issue by kevinrodriguez-io** [metaplex-foundation/js#155]
ERROR: Big integer literals are not available in the configured target environment (using VITE)  ("chrome87", "edge88", "es2019", "firefox78", "safari13.1").

Which seems to be caused by transitive dep: `noble-ed25519` used by `arbundles`

**Comment by lorisleiva** [comment]
Hi there 👋 

Did you follow this tutorial to get started with Vite, using the right polyfills?

https://github.com/metaplex-foundation/js-examples/tree/main/getting-started-vite

**Comment by kevinrodriguez-io** [comment]
Hi @lorisleiva Thanks a lot for this. IT WORKS 🚀.

**Comment by laurensV** [comment]
I am trying to get this to work for nuxt3 (vue) which is also using vite and nitro as a server processor. While it does work with the right polyfills for vite in nuxt development mode (`nuxt dev`) it doesn't work when I try to build it for production (`nuxt build`). Its failing in nitro it seems somewhere. Do I also need to change some of the nitro config?

```
ℹ Initializing prerenderer                                                                                   nitro 17:58:33

 ERROR  Rollup error: Transform failed with 93 errors:                                                       nitro 17:58:42
/metaplex/.nuxt/dist/server/index.592e07a8.js:31:12096: ERROR: Big integer literals are not available in the configured target environment ("es2019")
```
