### ISSUE TITLE
Minor type question

### ISSUE THREAD

**Issue by israelidanny** [metaplex-foundation/js#157]
I noticed a minor typing inconsistency while documenting the project.

`@solana/web3.js` exports a type alias named `TransactionSignature`:
```typescript
  /**
   * Transaction signature as base-58 encoded string
   */
  export type TransactionSignature = string;
```

In the following action (`sendTransaction`) we implicitly use that type alias because we return the output of `connection.sendRawTransaction`:
https://github.com/metaplex-foundation/js/blob/main/src/actions/transactions.ts#L29

On the other hand, in other actions we return `Promise<string>`:
https://github.com/metaplex-foundation/js/blob/main/src/actions/createMetadata.ts#L20

It's a very minor issue, and I see three easy outcomes:
1. We reexport / use `TransactionSignature` everywhere (the only pro: documentation will look a tiny bit cleaner, we wouldn't have to specify the return string is in fact a transaction signature verbosely everywhere)
2. We don't care :) 

Let me know - I can refactor the cases where we return `Promise<string>` if needed.

**Comment by aheckmann** [comment]
It's more helpful to users to reexport / use `TransactionSignature` everywhere. They'll be able to look up what that is and better understand what is happening. Ditch the `Promise<string>`
