### ISSUE TITLE
AbortController is undefined when using Metaplex JS 0.11.7 SDK in a NextJS app

### ISSUE THREAD

**Issue by zfaizal2** [metaplex-foundation/js#162]
We’re developing a library that uses the metaplex JS SDK as a dependency. When using this library in a nextJS app, the app errors out with the error below. 

When using this with a create-react-app based app however, things work just fine.

```
Uncaught TypeError: Cannot destructure property 'AbortController' of '(intermediate value)(intermediate value)(intermediate value)' as it is undefined.
nodeStackFrames.js:40
    getNodeError nodeStackFrames.js:40
    _callee$/< index.js:322
    (Async: setTimeout handler)
    _callee$ index.js:305
    Babel 10
        tryCatch
        invoke
        method
        asyncGeneratorStep
        _next
        (Async: promise callback)
    asyncGeneratorStep
        _next
        _asyncToGenerator
        _asyncToGenerator
        _initNext
    initNext index.js:375
    <anonymous> next-dev.js:46
    NextJS 6
        js
        factory
        __webpack_require__
        __webpack_exec__
        <anonymous>
        webpackJsonpCallback
    webpackJsonpCallback self-hosted:1162
    <anonymous> NextJS
```

Has anyone seen this before? What are potential steps or avenues to resolve this?

**Versions used**

@metaplex-foundation/js : 0.11.7

next-js: 12.0.7

**Comment by mayognaise** [comment]
@zfaizal2 Have you tried adding the code below?

next.config.js

```ts
/** @type {import('next').NextConfig} */

module.exports = {
  webpack: (config) => {
    config.resolve.fallback = { fs: false, path: false };
    return config;
  },
};

```

**Comment by zfaizal2** [comment]
@mayognaise Thanks for the suggestion, I tried that but still facing the same errors.

**Comment by mayognaise** [comment]
@zfaizal2 Could you share your code? I use exact same environment so I might be able to help you
(Although my nextjs verison is `12.1.6`)

**Comment by lorisleiva** [comment]
Hi there 👋 

Would you mind upgrading to version `0.12.0` and let me know if that fixes your issue?

**Comment by lorisleiva** [comment]
Hi there 👋

I'm going to close this due to inactivity but feel free to open a new issue using the latest version with updated information if you need to.

Thank you for your understanding.
