### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by 4akers21** [metaplex-foundation/js#163]
npm install @metaplex-foundation/js
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-shallow-renderer@16.14.1
npm WARN Found: react@18.0.0
npm WARN node_modules/react
npm WARN   peer react@"18.0.0" from react-native@0.69.1
npm WARN   node_modules/react-native
npm WARN     peer react-native@"*" from react-native-url-polyfill@1.3.0
npm WARN     node_modules/react-native-url-polyfill
npm WARN     1 more (@react-native-community/cli)
npm WARN   1 more (use-sync-external-store)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.0.0 || ^17.0.0" from react-shallow-renderer@16.14.1
npm WARN node_modules/react-shallow-renderer
npm WARN   react-shallow-renderer@"16.14.1" from react-native@0.69.1
npm WARN   node_modules/react-native
npm WARN
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.0.0 || ^17.0.0" from react-shallow-renderer@16.14.1
npm WARN   node_modules/react-shallow-renderer
npm WARN     react-shallow-renderer@"16.14.1" from react-native@0.69.1
npm WARN     node_modules/react-native
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\suppo\AppData\Local\npm-cache\_logs\2022-07-13T15_48_16_978Z-debug-0.log

what i do wrong ?

**Comment by lorisleiva** [comment]
Hi there 👋 

Could you please open a new issue with the steps to follow to reproduce this issue? Alternatively, would you please provide a public repository containing the minimum code required to replicate this issue?

Thank you for your understanding.
