### ISSUE TITLE
Mock Storage is not working

### ISSUE THREAD

**Issue by truedrju** [metaplex-foundation/js#169]
Issue on 0.12.0 and 11.7

Metaplex instantiation

```
mxconn = Metaplex.make(new Connection(clusterApiUrl("devnet")))
        .use(mockStorage())
```

1. store data and get URL: mxconn.storage().upload(file)
2. try to fetch that data with: mxconn.storage().upload("https://mockstorage.example.com/2NAHu8Kqqv7P9tiwisGZ")
3. Get Error `MetaplexError] Asset Not Found
>> Source: SDK
>> Problem: The asset at [https://mockstorage.example.com/2NAHu8Kqqv7P9tiwisGZ] could not be found.
>> Solution: Ensure the asset exists at the given path or URI.`

I am running this locally in a React App on React 18 on M1 Mac V12.2.1.

**Comment by lorisleiva** [comment]
Hi there 👋 

I'm assuming you mean `mxconn.storage().download("https://...")` for step 2.

Not sure why it wouldn't work for you though because the entire test suite uses the mock storage. 😕

**Comment by truedrju** [comment]
hmm not sure, I just wired in a real AWS driver and things worked, but I couldn't get mock example to work.  could have been a mixup on my end with the URLs I was passing in
