### ISSUE TITLE
Feature request - Web3.storage and Nft.storage support

### ISSUE THREAD

**Issue by stevenbarragan** [metaplex-foundation/js#171]
I think the correct way would be to upload the image to nft.storage and the matadata on Web3.storage.

**Comment by lorisleiva** [comment]
Hey Steven 👋 

I'm actually working right now on an _NFT.Storage_ Storage Driver which would make this possible. We don't have any immediate plan for Web3.Storage yet though.

**Comment by stevenbarragan** [comment]
fixed by https://github.com/metaplex-foundation/js/pull/191. Thanks @lorisleiva 🙏🏽
