### ISSUE TITLE
LoadNft() error

### ISSUE THREAD

**Issue by arthurbolsoni** [metaplex-foundation/js#173]
hi, i'm trying use the new method LoadNft() and have getting a error in toOriginalOrPrintEditionAccount.

`await mx.nfts().loadNft(nftLazy, {commitment: "finalized"});
`
![image](https://user-images.githubusercontent.com/21229921/179575854-90f77136-bfaa-4f8b-a080-c942ff4e8aa3.png)

i'm did try rewrite me method and the error come from toOriginalOrPrintEditionAccount(), later it i lost me on the code.

Using: reactjs

**Comment by blockiosaurus** [comment]
I believe this is an error in the index passed in here https://github.com/metaplex-foundation/js/blob/52e698df76518113dce9e3155ae6b7b5239db484/packages/js/src/plugins/nftModule/loadNft.ts#L44
The accounts are constructed as an array of 2 but the index of 2 is being used to retrieve the edition account. Changing this to an index of 1 locally at least prevents a failure, but I haven't checked the edition info for accuracy.

**Comment by lorisleiva** [comment]
Well, that's embarrassing. I promise I know how to count. 😅 

I'll fix this asap.

**Comment by lorisleiva** [comment]
Fixed and published as `0.12.4`. 🚀
