### ISSUE TITLE
How do we validate safety deposit boxes using this SDK?

### ISSUE THREAD

**Issue by tengu-br** [metaplex-foundation/js#174]
As described in the official documentation [here](https://docs.metaplex.com/architecture/basic_flow), the 11th step to launch an auction is to call the `validate_safety_deposit_box` endpoint on the metaplex program, but I can't seem to find a way to do that using the functions provided by this SDK nor any tests that show how to do it manually.

**Comment by freahmanCoder** [comment]
same here

**Comment by akkySrivastava** [comment]
I'm also looking for the same.

**Comment by AnuragSinghKushwah** [comment]
Same here

**Comment by AmmarKhalid123** [comment]
@tengu-br @AnuragSinghKushwah @akkySrivastava  @freahmanCoder  Have you guys been able to do the steps from 5-10 of launching an auction using metaplex/js sdk? If yes, can you guide me the methods you've used in doing so ?

**Comment by littleV** [comment]
same here.

**Comment by aliiqbal436** [comment]
Same here i did write code about it but getting this error.
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/36224038/158068401-f8ce09ba-6882-4c48-b8ee-6f3a27751572.png">

**Comment by aliiqbal436** [comment]
@AmmarKhalid123 This will help you. I am also following it.

https://github.com/blockforce-official/cryptum-sdk/blob/844fc8428cb60385c13a818ed2ad9125d1e8cb85/src/services/blockchain/solana/index.js#L421

**Comment by AmmarKhalid123** [comment]
I think the file @aliiqbal436 mentioned in the above reply contains a function validateAuction @LineNo: 618, which is basically validating the safety deposit box as mentioned in the metaplex docs for launching auction in step 11.

**Comment by aliiqbal436** [comment]
@AmmarKhalid123 Yes it is but I'm getting the error..
Do you have the exact code of it?

**Comment by ShuklaSushant** [comment]
I am also struggling on this from last many days...`validateAuction` from https://github.com/blockforce-official/cryptum-sdk/blob/844fc8428cb60385c13a818ed2ad9125d1e8cb85/src/services/blockchain/solana/index.js#L618 uses solana native transaction & gives me "Assert Error" on ` const safetyDepositConfigArgs = new SafetyDepositConfig({`

**Comment by ShuklaSushant** [comment]
> I'm also looking for the same.

@akkySrivastava @aliiqbal436 @AmmarKhalid123 Have you got solution for this problem?

**Comment by aliiqbal436** [comment]
@ShuklaSushant nope.

**Comment by ShuklaSushant** [comment]
> > Same here i did write code about it but getting this error.
> > <img alt="image" width="971" src="https://user-images.githubusercontent.com/36224038/158068461-65c5bfb0-51d7-4725-a8ae-96887660278e.png">
> 
> @aliiqbal436 which metadata are you passing in the validate auction? I was passing the metadata returned from addTokenToVault, and was receiving the same error. Change that to the metadata value returned from mintNFT function and it will hopefully resolve

@AmmarKhalid123 I am also stuck on this error
i am passing `TokenMetadata` of NFT which is in vault , is this wrong?

**Comment by bassmoneynft** [comment]
I am having this same error. I am passing the PDA from the Metaplex Metadata program: `await Metadata.getPDA(mint)` where `mint` is the mint key from `mintNFT()` ... any more insight would be great.

**Comment by AmmarKhalid123** [comment]
@ShuklaSushant  I'm passing the "metadata" received in response when I mint NFT using mintNFT function from the sdk and working perfect for me

**Comment by ShuklaSushant** [comment]
> @ShuklaSushant I'm passing the "metadata" received in response when I mint NFT using mintNFT function from the sdk and working perfect for me

@AmmarKhalid123 Thanks for response
My observation : When i use MasterEdition to create Vault, Auction & Auction Manager then it work like a charm
But When i use Print of MasterEdition then it doesn't work & give same error which is faced by everyone.

I am still wondering why?

**Comment by ShuklaSushant** [comment]
I am studying all the transactions of `instantSale` , so far i have found `9 out of 11` , can anyone help about last 2 transactions

**Comment by bassmoneynft** [comment]
Can confirm passing `metadata` from `mintNFT()` response corrects the 'Invalid Creator Index' error from `ValidateSafetyDepositBoxV2`.

**Comment by nurav97** [comment]
![brave_5i3Bf9ODoi](https://user-images.githubusercontent.com/89197239/163365379-bcae2bbe-a9b5-4bbb-8069-3c21d0fc2496.png)


Did anyone get this error on validate auction instruction
