### ISSUE TITLE
No ability to set properties.category or animationURL in MetaData

### ISSUE THREAD

**Issue by truedrju** [metaplex-foundation/js#180]
I see the token metadata standard supports a properties.category and animationURL for non static file types via [https://docs.metaplex.com/programs/token-metadata/changelog/v1.0#json-structure](url)

My use case is I am uploading a 3d model in gltf format but when I view the NFT in phantom, the file does not render correctly -- format is supported as per doc https://docs.phantom.app/best-practices/tokens/supported-media-types

I have tried naming the file correctly with .gltf extension and tried setting contentType to the correct mime types both on the file object and as args the toMetaplexFileFromBrowser : "model/gltf" , "gltf", "model/gtlf+json"

I am assuming that this is due to the correct properties not being set correctly in the MetaPlex File here: https://github.com/metaplex-foundation/js/blob/1088ed287dd4ca70bce51b442beeed0fdd72c5b1/src/plugins/storageModule/MetaplexFile.ts#L5-L13

Is there a recommended way for me to set the meta data correctly on this?

**Comment by lorisleiva** [comment]
Hey 👋 I'm not sure I understand what is going wrong. The `MetaplexFile` is just a wrapper around a `Buffer` with extra context. You simply need to set up your JSON Metadata in a way that lets Phantom know about your 3D model if they support it. Could you provide an example of your current metadata and what you'd expect it to be instead?

**Comment by ninnjak** [comment]
As @lorisleiva says, you just need to add the properties you want when you upload the metadata here is an example:

```typescript
const { metadata } = await metaplex
    .nfts()
    .uploadMetadata({
      name: "My NFT",
      description: "My NFT description.",
      seller_fee_basis_points: 500,
      image: "https://link-to-image?ext=png",
      animation_url: "https://link-to-animation?ext=mp4",
      properties: {
        files: [
          {
            uri: "https://link-to-image?ext=png",
            type: "image/png",
          },
          {
            uri: "https://link-to-animation?ext=mp4",
            type: "video/mp4",
          },
          {
            uri: "https://link-to-3d-model?ext=glb",
            type: "vr/glb",
          },
        ],
        category: "vr",
        creators: [
          {
            address: "my-wallet-adress",
            share: 100,
          },
        ],
      },
    })
    .run();
```

**Comment by lorisleiva** [comment]
Thank you for your help @ninnjak!

I'm closing this but feel free to reopen or create a new issue with more information on the expected behaviour if needed.
