### ISSUE TITLE
How do you mint?

### ISSUE THREAD

**Issue by PomegranateApps** [metaplex-foundation/js#186]
I've been using this code to mint Solana NFT's in my own project, but is it possible to use this API to do the same?
https://github.com/metaplex-foundation/candy-machine-ui/blob/main/src/candy-machine.ts#L371

**Comment by lorisleiva** [comment]
```ts
const { nft } = await metaplex.candyMachines().mint(...).run();
```

🙂

**Comment by PomegranateApps** [comment]
Is there documentation for this somewhere?

**Comment by lorisleiva** [comment]
Not yet, soon :)
