### ISSUE TITLE
Supplied an invalid creator index to empty payment account

### ISSUE THREAD

**Issue by aliiqbal436** [metaplex-foundation/js#188]
**I am getting this error while validating auction.**

**Screenshots**
<img width="971" alt="image" src="https://user-images.githubusercontent.com/36224038/158068455-418b7344-2adf-434a-ac49-4bc1cacc713f.png">

**Comment by AmmarKhalid123** [comment]
@aliiqbal436  which metadata are you passing in the validate auction? I was passing the metadata returned from addTokenToVault, and was receiving the same error. Change that to the metadata value returned from mintNFT function and it will hopefully resolve

**Comment by ShuklaSushant** [comment]
Duplicate issue : https://github.com/metaplex-foundation/js/issues/174

**Comment by aliiqbal436** [comment]
@AmmarKhalid123 we are passing token metadata. 
And we have completed the create auction work and it's working.

**Comment by aliiqbal436** [comment]
@AmmarKhalid123  We need any help let me know.

**Comment by AmmarKhalid123** [comment]
@aliiqbal436  have you been able to run end auction successfully?

**Comment by aliiqbal436** [comment]
@AmmarKhalid123 not we are working on it.
Just created and start the auction successfully yet.

**Comment by aliiqbal436** [comment]
@AmmarKhalid123 have to done with finish auction work?

**Comment by AmmarKhalid123** [comment]
Yes I'm done with finish auction.

**Comment by ShuklaSushant** [comment]
@AmmarKhalid123 I am struggling with `instant Sale` ,have you completed that?

**Comment by AmmarKhalid123** [comment]
> 

I haven't used their instantSale method, since it doesn't suit our requirements, so I'm not sure about that. Also in my current setup, the steps you mentioned are same to launch an auction

**Comment by aliiqbal436** [comment]
@ShuklaSushant have you started auction using `actions` methods? then don't us that it's not working.
Create auction using classes and instructions. for example import classes like that.

`const auctionInstruction new programs.auction.CreateAuction(CreateArgeParams);
`
and sign and send transaction.

**Comment by nurav97** [comment]
@aliiqbal436  can you post a sample code for single NFT auction using metaplex js it would be of great help
