### ISSUE TITLE
Syntax issues with @bundlr-network/client in a firebase project

### ISSUE THREAD

**Issue by skmanish** [metaplex-foundation/js#189]
I am using @metaplex-foundation/js as a part of my firebase cloud function that recovers whether a wallet owns an NFT or now. I am seeing the following as predeploy errors:
```
node_modules/@metaplex-foundation/js/node_modules/@bundlr-network/client/build/common/types.d.ts:26:5 - error TS1131: Property or signature expected.

26     get address(): string;
       ~~~

node_modules/@metaplex-foundation/js/node_modules/@bundlr-network/client/build/common/types.d.ts:26:9 - error TS1005: ';' expected.

26     get address(): string;
           ~~~~~~~

node_modules/@metaplex-foundation/js/node_modules/@bundlr-network/client/build/common/types.d.ts:26:18 - error TS1005: ';' expected.

26     get address(): string;
```

**Comment by lorisleiva** [comment]
Hi there 👋 
 
Could you please open a new issue with the steps to follow to reproduce this issue? Alternatively, would you please provide a public repository containing the minimum code required to replicate this issue?
 
Thank you for your understanding.
