### ISSUE TITLE
build error in react-native 0.68.2

### ISSUE THREAD

**Issue by SonDN-DDS** [metaplex-foundation/js#190]
TypeError: Conversion from 'BigInt' to 'number' is not allowed. 
Test@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.panwallet.app.dev:618752:26
RCTView
View
RCTView
View
AppContainer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.panwallet.app.dev:79094:36
panWallet(RootComponent)@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.panwallet.app.dev:85778:28
 WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[11], "@metaplex-foundation/js").Metaplex')
_callee2$@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.panwallet.app.dev:512465:87
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.panwallet.app.dev:24113:23
@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.panwallet.app.dev:24093:34
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.panwallet.app.dev:24113:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.panwallet.app.dev:24151:30
@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.panwallet.app.dev:24175:19
tryCallTwo@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.panwallet.app.dev:28570:9
doResolve@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.panwallet.app.dev:28734:25
Promise@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.panwallet.app.dev:28593:14
callInvokeWithMethodAndArg@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.panwallet.app.dev:24174:33
@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.panwallet.app.dev:24179:157
@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.panwallet.app.dev:24265:69
_callee2@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.panwallet.app.dev:512461:38
@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.panwallet.app.dev:618753:75
commitHookEffectListMount@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.panwallet.app.dev:15501:38
commitPassiveMountOnFiber@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.panwallet.app.dev:16701:44
commitPassiveMountEffects_complete@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.panwallet.app.dev:16666:40
commitPassiveMountEffects_begin@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.panwallet.app.dev:16653:47
commitPassiveMountEffects@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.panwallet.app.dev:16641:40
flushPassiveEffectsImpl@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.panwallet.app.dev:17971:34
flushPassiveEffects@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.panwallet.app.dev:17928:43
performSyncWorkOnRoot@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.panwallet.app.dev:17346:28
performSyncWorkOnRoot@[native code]
flushSyncCallbacks@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.panwallet.app.dev:7679:36
flushSyncCallbacksOnlyInLegacyMode@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.panwallet.app.dev:7660:29
scheduleUpdateOnFiber@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.panwallet.app.dev:17041:49
updateContainer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.panwallet.app.dev:19435:41
render@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.panwallet.app.dev:20011:24
renderApplication@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.panwallet.app.dev:85730:78
run@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.panwallet.app.dev:85460:64
runApplication@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.panwallet.app.dev:85518:28
__callFunction@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.panwallet.app.dev:3202:36
@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.panwallet.app.dev:2926:31
__guard@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.panwallet.app.dev:3153:15
callFunctionReturnFlushedQueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.panwallet.app.dev:2925:21
callFunctionReturnFlushedQueue@[native code]

info Opening /Users/ngocson/React-Native/TestGit/panWallet/node_modules/noble-ed25519/index.js with idea
error spawn idea ENOENT
info 
 How to fix: 
  When you see Red Box with stack trace, you can click any 
  stack frame to jump to the source file. The packager will launch your 
  editor of choice. It will first look at REACT_EDITOR environment 
  variable, then at EDITOR.
  To set it up, you can add something like 
  export REACT_EDITOR=atom to your ~/.bashrc or ~/.zshrc depending on 
  which shell you use.
![Screen Shot 2022-07-25 at 11 55 08](https://user-images.githubusercontent.com/90590167/180701333-0acadcfa-eb08-4692-ad86-3c583f4adc50.png)

**Comment by lorisleiva** [comment]
Hi there 👋 
 
Could you please open a new issue with the steps to follow to reproduce this issue? Alternatively, would you please provide a public repository containing the minimum code required to replicate this issue?
 
Thank you for your understanding.
