### ISSUE TITLE
undefined, get nft metadata

### ISSUE THREAD

**Issue by Harold-coder** [metaplex-foundation/js#193]
When I try to run the simple code below from the solana cookbook, I simply get "undefined".
I am sure I have metaplex sdk and solana/web3 installed. 

`import { Metaplex, keypairIdentity } from "@metaplex-foundation/js";
import { Connection, clusterApiUrl, Keypair, PublicKey } from "@solana/web3.js";

(async () => {
  const connection = new Connection(clusterApiUrl("devnet"));
  const keypair = Keypair.generate();

  const metaplex = new Metaplex(connection);
  metaplex.use(keypairIdentity(keypair));

  const mint = new PublicKey("6q52hR8P1AANELCnwHx38V4PvnxmdotChCrK8uCGoAF");

  const nft = await metaplex.nfts().findByMint(mint);

  console.log(nft.metadata);
  /*
  {
    name: 'SMB #139',
    symbol: 'SMB',
    description: 'SMB is a collection of 5000 randomly generated 24x24 pixels NFTs on the Solana Blockchain. Each SolanaMonkey is unique and comes with different type and attributes varying in rarity.',
    seller_fee_basis_points: 600,
    image: 'https://arweave.net/tZrNpbFUizSoFnyTqP4n2e1Tf7WvP3siUwFWKMMid_Q',
    external_url: 'https://solanamonkey.business/',
    collection: { name: 'SMB Gen2', family: 'SMB' },
    attributes: [
      { trait_type: 'Attributes Count', value: 2 },
      { trait_type: 'Type', value: 'Solana' },
      { trait_type: 'Clothes', value: 'Orange Shirt' },
      { trait_type: 'Ears', value: 'None' },
      { trait_type: 'Mouth', value: 'None' },
      { trait_type: 'Eyes', value: 'Cool Glasses' },
      { trait_type: 'Hat', value: 'None' }
    ],
    properties: {
      files: [ [Object], [Object] ],
      category: 'image',
      creators: [ [Object] ]
    }
  }
  */
})();
`

**Comment by ninnjak** [comment]
Be sure to check the [README](https://github.com/metaplex-foundation/js/blob/main/README.md) for the most recent examples as the API has changed and could potentially change in the future.

To access the metadata based on your example you would do the following:

```typescript
const mint = new PublicKey("6q52hR8P1AANELCnwHx38V4PvnxmdotChCrK8uCGoAF");

const nft = await metaplex.nfts().findByMint(mint).run();

console.log("METADATA: ", nft.json);
```

**Comment by Harold-coder** [comment]
Thank you immensely for both solving my issue and helping me solve later issue. 

Have a great week!
