### ISSUE TITLE
Loading NFT errors out due to edition account not being available

### ISSUE THREAD

**Issue by skulltech** [metaplex-foundation/js#194]
e.g. I got this error when I tried to load the NFT with mint `6P7U2KK1PMh3oeYBALftbDeUoNTPE2rioqhb1wwZwFS2`.

```
AccountNotFoundError [MetaplexError]: Account Not Found
>> Source: SDK
>> Problem: The account of type [MasterEditionV1 | MasterEditionV2 | Edition] was not found at the provided address [3QEd2d2L2q9Q8LuTnzV1reYFvZcSQxQ5iVvbsQ7D5D41].
>> Solution: Ensure the provided address is correct and that an account exists at this address.
```

I think a robust solution would be making the `edition` field optional, and in case it isn't available keep that field empty and return a loaded NFT with rest of the fields loaded.

**Comment by zhaodong-wang** [comment]
I had the same error, how can I get the nft data in this case?

**Comment by dn-l** [comment]
Got the same error

**Comment by lorisleiva** [comment]
Hi there 👋 

Could you share the version of the SDK and the code you're using because the SDK supports both NFTs and SFTs. It's worth noting that an NFT without an edition account is, by definition, not an NFT. However, as I said, the SDK should also support SFTs.

**Comment by dn-l** [comment]
@lorisleiva 
```
    "@metaplex-foundation/js": "^0.15.0",
```

```ts
    const { nft } = await metaplex
        .nfts()
        .create({
          tokenOwner,
          name: "Some name",
          uri: "https://someuri.com",
          sellerFeeBasisPoints: 6969,
          creators: [
            {
              address: keypair.publicKey,
              verified: true,
              share: 0,
            },
            {
              address: new PublicKey(
                "some key"
              ),
              verified: false,
              share: 100,
            },
          ],
        })
        .run();
```

**Comment by lorisleiva** [comment]
Hi @dn-l, I'm confused I thought this issue was to do with loading NFTs / SFTs and not creating them.

I'm going to close this issue for now since it seems they are referencing different issues on different versions but please feel free to open a new issue using the latest version with updated information if you need to.

Thank you for your understanding.
