### ISSUE TITLE
Unable to mint v0.13.2

### ISSUE THREAD

**Issue by mjzuppe** [metaplex-foundation/js#197]
On one of the recent updates, the create NFT functionality now returns an error when running:
`await metaplex.nfts().create({ uri, name, sellerFeeBasisPoints }).run();`

Error:
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined

Something perhaps in the CreateNFTBuilder process that was updated?

![Screen Shot 2022-07-26 at 2 28 28 PM](https://user-images.githubusercontent.com/15622396/181083960-ed819e42-2cea-42b9-bad5-a6a08c8fa4a0.png)

**Comment by rastrent** [comment]
Creating NFT's is working for me with 13.2. Are you sure something else isn't up here? Mind posting some more context for your code? 

Also just in case some things got out of sync you can always try removing the node modules folder and running yarn/npm again. Sometimes things get messed up there.

**Comment by mjzuppe** [comment]
@rastrent Yup, that was it! Embarrassed I totally forgot to try that. Thanks for your help.
