### ISSUE TITLE
Can't import the named export 'ACCOUNT_SIZE' from non EcmaScript module 

### ISSUE THREAD

**Issue by HarshaGunathilake** [metaplex-foundation/js#200]
we found some issues in adding the upload function 
./node_modules/@metaplex-foundation/js/dist/esm/plugins/tokenModule/gpaBuilders.mjs
Can't import the named export 'ACCOUNT_SIZE' from non EcmaScript module (only default export is available)

**Comment by AmmarKhalid123** [comment]
Have you found any workaround? @HarshaGunathilake

**Comment by lorisleiva** [comment]
Hey there 👋 

Could you please provide more information on your environment?

This is likely an issue regarding ESM and CJS not playing nicely together and the more information I have about your bundler, the better.

Also, did you check the `js-examples` repository for getting started with various bundlers?

https://github.com/metaplex-foundation/js-examples

**Comment by prateekvasi** [comment]
I have same issue.
./node_modules/@metaplex-foundation/js/dist/esm/plugins/tokenModule/gpaBuilders.mjs
Can't import the named export 'ACCOUNT_SIZE' from non EcmaScript module (only default export is available)

I'm using: [Getting Started with Metaplex and CRA 5](https://github.com/metaplex-foundation/js-examples/blob/main/getting-started-react-cra5) (React and Webpack 5)

Please help!

**Comment by prateekvasi** [comment]
Can you Please give some solution? @lorisleiva

**Comment by lorisleiva** [comment]
Hey there 👋  I'll have a look at this issue as soon as I can but for now, I would suggest using Next.js since it is usually much easier to set up with the SDK than CRA5.

**Comment by lorisleiva** [comment]
Looking at this again and it could be to do with the fact that some of the examples in the `js-examples` repository are not using the latest version of the SDK and the latest version of whichever framework they use. Any help on that front would be more than appreciated. 🙏

**Comment by zain-ekkel** [comment]
Hey, any update on this ?
