### ISSUE TITLE
metaplex-foundation does not work in react app. 

### ISSUE THREAD

**Issue by Harold-coder** [metaplex-foundation/js#203]
I am trying to simply import the sdk on my react app that works perfectly and every time I add this line at the beginning:

import { Metaplex, keypairIdentity } from "@metaplex-foundation/js";

My webApp becomes a blank screen and my console tells me:

types.js:22 Uncaught ReferenceError: Buffer is not defined

But without this simple line, everything works well.

**Comment by lorisleiva** [comment]
Hi there 👋 

Sounds like you need to import some polyfills.

Please check the following repository for some getting started examples:

https://github.com/metaplex-foundation/js-examples
