### ISSUE TITLE
Error executing sale

### ISSUE THREAD

**Issue by fallenangel2305** [metaplex-foundation/js#216]
code

   const tx = await metaplex
          .auctions()
          .builders()
          .executeSale({ auctionHouse, bid, listing })
          .sendAndConfirm(metaplex);

error
TypeError: metaplex.auctions(...).builders(...).executeSale is not a function
    at _callee$ (index.tsx?07ff:624:12)
    at tryCatch (runtime.js?ecd4:45:16)
    at Generator.invoke [as _invoke] (runtime.js?ecd4:274:1)
    at prototype.<computed> [as next] (runtime.js?ecd4:97:1)
    at asyncGeneratorStep (index.tsx?07ff:1:1)
    at _next (index.tsx?07ff:1:1)

**Comment by lorisleiva** [comment]
The Auction House module is still being worked on. It will be properly released and documented in due time. Thank you for your patience.

**Comment by fallenangel2305** [comment]
thanks for the answer i just want to make sure i'm doing it right? there is a auction().for().executeSale() and auction().builders().executeSale() why is that

**Comment by lorisleiva** [comment]
`builders()` give you the underlying transaction builder so you can edit it as you like before sending it to the cluster.
