### ISSUE TITLE
Please mark https://www.npmjs.com/package/@metaplex-foundation/js-next as deprecated

### ISSUE THREAD

**Issue by mikemaccana** [metaplex-foundation/js#225]
Currently https://www.npmjs.com/package/@metaplex-foundation/js-next seems newer than https://www.npmjs.com/package/@metaplex-foundation/js - since it's `js-next`, right?

But `js-next` is actually older than `js`, from what I can see.

It would be good to mark https://www.npmjs.com/package/@metaplex-foundation/js-next as deprecated (which can be [done via the npm command](https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions) ) and edit the README for `js-next` to say `js-next` is deprecated.

**Comment by lorisleiva** [comment]
Done! Thank you for raising this. 🍺

**Comment by mikemaccana** [comment]
Brilliant thanks Loris! ⭐️
