### ISSUE TITLE
Types seem to be missing for NftClient methods (other types are fine) in VScode

### ISSUE THREAD

**Issue by mikemaccana** [metaplex-foundation/js#227]
Using `@metaplex-foundation/js@0.14.0` in vscode, while the `NftClient` object itself is typed (so I can see the type definitions are working), all the methods inside `NftClient` are of `any` type, have no parameters, and return `any`.

![image](https://user-images.githubusercontent.com/172594/183981579-55f6bce6-f84f-4115-977f-4a096bcec5aa.png)

![image](https://user-images.githubusercontent.com/172594/183981846-65985e40-9371-4fab-a4ce-7780344f786e.png)

I'm not sure what's going on here, I can see types like `CreateNftOutput` exist in `js/dist/types/plugins/nftModule/createNft.d.ts` but for some reason the way the types are created doesn't seem to agree with vscode.

**Comment by mikemaccana** [comment]
PS I can product a standalone project reproducing this behavior if needed, just let me know!

**Comment by lorisleiva** [comment]
Oh no that's annoying. Thanks for raising this I'll investigate asap. This must be due to a recent refactoring that moves the client methods directly into the operation files so everything is in one place. But I didn't know VS Code was not going to be happy about this. I'll see if I can be more explicit when I link the method with the class.

**Comment by lorisleiva** [comment]
This should now be fixed in version [`0.15`](https://github.com/metaplex-foundation/js/releases/tag/js%2Fv0.15.0). 🚀

**Comment by mayoyml** [comment]
@lorisleiva Thank you always! It seems like the version isn't ready on npm yet? I got this when installing it:

```
yarn add @metaplex-foundation/js@0.15.0
...
[1/4] 🔍  Resolving packages...
Couldn't find any versions for "@metaplex-foundation/js" that matches "0.15.0"
```

**Comment by lorisleiva** [comment]
Ah I'm an idiot, I forgot to publish. Thanks for raising this! It should be published now. 🍺

**Comment by mayoyml** [comment]
@lorisleiva yay!! HEAVEN!
<img width="818" alt="image" src="https://user-images.githubusercontent.com/47791310/184942988-a1982775-47b3-4179-b9fa-4bd61a9375d3.png">

**Comment by mikemaccana** [comment]
Thanks all! 💖
