### ISSUE TITLE
When creating a candy machine 0x52 eh

### ISSUE THREAD

**Issue by aeaa1998** [metaplex-foundation/js#238]
The following error occurs when I create a candy machine with a collection.

Maybe I am missing something?  I've tried creating the nft with the minimum input and it does not work.
The Metaplex identity is with my wallet

<img width="1675" alt="image" src="https://user-images.githubusercontent.com/47725760/184791125-e1188ace-c0c1-42f4-b7fe-5ca9a949dba1.png">

Code to create the nft
```js
const {uri, metadata} = await metaplex.value.nfts().uploadMetadata({
  name: title,
  description: description,
  // image: metafile,
  symbol: title,
}).run()
 
const {
  nft,
  mintAddress,
  metadataAddress,
  masterEditionAddress,
  tokenAddress,
} = await metaplex.value
  .nfts()
  .create({
    uri,
    name: title,
    maxSupply: null,
    sellerFeeBasisPoints: 200,
    // isCollection: true
  })
  .run();
```

Code to create candy machine
```js
     const { candyMachine } = await client
        .create({
          price: sol(1),
          itemsAvailable: toBigNumber(1),
          sellerFeeBasisPoints: 500,
          collection: nft.address,
        })
        .run();

```

**Comment by lorisleiva** [comment]
Hi there 👋 

Sorry for the late reply! Are you still experiencing this issue with the latest SDK version?

This should at least translate Program errors now so you should have a better understanding of what the Program is complaining about.

**Comment by aeaa1998** [comment]
Hi @lorisleiva  thanks for your response 😁. 
I've found out that the problem was that the nft I was using to create the candy machine with the collection had an infinite supply. 
Thanks for the feedback. 🙌🏻
