### ISSUE TITLE
Documentation broken link

### ISSUE THREAD

**Issue by Mayzz03** [metaplex-foundation/js#245]
The link to the createNft parametters list is broken.

https://github.com/metaplex-foundation/js/blob/main/packages/js/src/plugins/nftModule/createNft.ts

**Comment by 0xChief** [comment]
Correct link is https://github.com/metaplex-foundation/js/blob/main/packages/js/src/plugins/nftModule/NftClient.ts

**Comment by ninnjak** [comment]
I believe this is actually the correct link, same file just refactored folder structure:

https://github.com/metaplex-foundation/js/blob/main/packages/js/src/plugins/nftModule/operations/createNft.ts

**Comment by lorisleiva** [comment]
I'm currently working on API references generated by typedoc.

I'll update docs with these links instead but here's an example for `nfts().create()`:

https://metaplex-foundation.github.io/js/classes/js.NftClient.html#create
