### ISSUE TITLE
How to recover arweave links generated on failure of metaplex.storage().uploadAll(metaplexFilles)?

### ISSUE THREAD

**Issue by HereFrank** [metaplex-foundation/js#256]
These is the case, supposed that I want to generate 10.000 arweave links and I make a code like these:
`const imageLinks = await metaplex.storage().uploadAll(metaplexFiles)` 
being metaplexFile an array of metaplex files with images that I want to convert to arweave links... 
Seeing the code here:
https://github.com/metaplex-foundation/js/blob/1827aaea479106a966ba026fbc97fe4a78c240c3/packages/js/src/plugins/bundlrStorage/BundlrStorageDriver.ts#L105
I wonder:

- what happens if the transaction fails when I'm generating the 10.000 arweave links and I just generate 5000 arweave links?

In these case, due that the code are using a `PromiseAll` I think that the transaction will fail, but even that happen the user will be charge for the 5000 arweave links, and I think that I'm unable to get that arweave links, since  the code is using `PromiseAll` behind the scenes.
I think these a issue right?
I mean, `const imageLinks = await metaplex.storage().uploadAll(metaplexFiles)` should provide some type of error handling to maybe obtain the 5000 arweave links generated in my example, right? 
And maybe a way to handle the concurrency of promises....

**Comment by lorisleiva** [comment]
Hi there 👋 

That's correct, currently, the bulk upload mechanism is fairly rudimentary and could do with a better error and retry logic.

There's too much to do on this SDK for us to focus on this right now but it is something I'd like the SDK to support at some point.

In the meantime, I suggest working with the `upload` method and implement your own custom error handling.

Thanks for raising this.

**Comment by lorisleiva** [comment]
I'm going to mark this as a "feature request" since we're now logging these using Canny.io so people can upvote and comment on their favourite feature requests. Thanks for understanding. 🌸
