### ISSUE TITLE
How do I launch tests?

### ISSUE THREAD

**Issue by 5elfle5** [metaplex-foundation/js#267]
What I did:
1. cloned this repo
2. "yarn install", "yarn build" in root
3. launched solana-test-validator (also tried not launching it)
4. yarn test

I see this error:
"Unable to fetch address labels. , is amman running with the relay enabled? If not please start it as part of amman in a separate terminal via `amman start` Make sure to set `relay: { enabled: true }` in `.ammanrc.js`."
I don't understand how to install amman, "npm i -g amman" didn't help.

I'm using Mac M1, node v18.6.0

**Comment by lorisleiva** [comment]
Hi there 👋 

You need to run `yarn amman:start` to start a local validator with all the Metaplex programs loaded.
