### ISSUE TITLE
add instant sale

### ISSUE THREAD

**Issue by Merrick17** [metaplex-foundation/js#269]
How can i make an instant sale using this package ? 
I googled and searched everything and didn't  find a solution...

**Comment by lorisleiva** [comment]
Hi there 👋 

We're still working on the Auction House module at the moment but you may have a look at the [API references](https://metaplex-foundation.github.io/js/classes/js.AuctionHouseClient.html) to see what's been implemented and how to use it.

When the module will be ready, we'll work on its documentation so this process will be easier.

Thank you for your understanding.
