### ISSUE TITLE
Error AuctionHouseProgram > Account is already initialized

### ISSUE THREAD

**Issue by Merrick17** [metaplex-foundation/js#270]
i'm trying to upload list to an exisiting aution house , like this 
` const auctionHouse = await metaplex
      .auctions()
      .findAuctionHouseByCreatorAndMint(keypair.publicKey, WRAPPED_SOL_MINT)
      .run();
    const result = await metaplex
      .auctions()
      .for(auctionHouse)
      .list({
        mintAccount: new PublicKey(
          "Fn1Ej1BLwkWidWesz4f5FjEF6pyUSZixLspMQ8UeTnQp"
        ),
        price: sol(1.5),
      })
      .run();` 
      however I always get a an error ,Error AuctionHouseProgram > Account is already initialized.
      I can't find documentation or a solution for it

**Comment by lorisleiva** [comment]
Hi there 👋 

This is a duplicate of #286.

I know this issue was raised first but since the other one has more activity, I'll close this one instead.

Thank you for you understanding.
