### ISSUE TITLE
Can't import the named export 'ACCOUNT_SIZE' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by prateekvasi** [metaplex-foundation/js#285]
I have issue.
./node_modules/@metaplex-foundation/js/dist/esm/plugins/tokenModule/gpaBuilders.mjs
Can't import the named export 'ACCOUNT_SIZE' from non EcmaScript module (only default export is available)

Installation done from here: https://github.com/metaplex-foundation/js

Also
I'm using: [Getting Started with Metaplex and CRA 5](https://github.com/metaplex-foundation/js-examples/blob/main/getting-started-react-cra5) (React and Webpack 5)

Please help!

**Comment by lorisleiva** [comment]
Duplicate of #200
