### ISSUE TITLE
MetaplexError: AuctionHouseProgram > Account is already initialized"

### ISSUE THREAD

**Issue by samia-invozone** [metaplex-foundation/js#286]
I'm trying to list NFT by the following code & getting an error(Account is already initialized).
`const { listing, sellerTradeState, receipt } = await metaplex
        .auctions()
        .for(auctionHouse)
        .list({
          mintAccount: new PublicKey(mintAddress),
          price: sol(price),
          printReceipt: true,
        })
        .run();`

**Comment by lorisleiva** [comment]
Hey there 👋 

Did you run this snippet of code more than once by any chance? This error usually means that a listing already exists with these settings. Errors will be clearer in the future sorry about that.

**Comment by samia-invozone** [comment]
Nope, It's giving this error from the very 1st time. I have also tried to list nft by new mint address but still getting the same error.

**Comment by lorisleiva** [comment]
Could you please provide a small public repo with the code necessary to reproduce this?

**Comment by samia-invozone** [comment]
Issue resolved. Thank you

**Comment by agtzdimi** [comment]
Hello @samia-invozone, I faced the issue as well and did not resolve it. Could you elaborate on the fix you made? Or why this was caused?

**Comment by zaxozhu** [comment]
@agtzdimi May I ask you to run this command with **skipPreflight: true** property and share the logs? It will help to make the issue more detailed.

Like in example:

```
const { listing, sellerTradeState, receipt } = await metaplex
  .auctions()
  .for(auctionHouse)
  .list({ 
    mintAccount: new PublicKey(mintAddress), 
    price: sol(price), 
    printReceipt: true, 
    **confirmOptions: {
     skipPreflight: true
    }**
}) .run();
```

**Comment by samia-invozone** [comment]
> Hello @samia-invozone, I faced the issue as well and did not resolve it. Could you elaborate on the fix you made? Or why this was caused?

When you create your auction house, you also get your Auction House Fee Account. This fee account must be funded. Try to airdrop SOL into this. Hope so it will work out

**Comment by agtzdimi** [comment]
Thank you @samia-invozone
I will try it out today, although I remember I did an initial airdrop, cause I pasted the code from the unit test.
In any case, I will post the outcome here @zaxozhu. Much appreciated guys

**Comment by leonidstrelok** [comment]
And which version of metaplex do you use? I just use metaplex too, but it's called a little differently for me. More specifically, metaplex.auctionHouse().create(). As an example, creating an auction. But what to do next, I don't even have a clue in what order you need to create all this. Tell me please

**Comment by thangtranth** [comment]
> const { listing, sellerTradeState, receipt } = await metaplex .auctions() .for(auctionHouse) .list({ mintAccount: new PublicKey(mintAddress), price: sol(price), printReceipt: true, }) .run();



> > Hello @samia-invozone, I faced the issue as well and did not resolve it. Could you elaborate on the fix you made? Or why this was caused?
> 
> When you create auction house, you also get your Auction House Fee Account. This fee account must be funded. Try to airdrop SOL into this. Hope so it will work out

Thank you so much. You really save my day.

**Comment by sahityaeeshufynd** [comment]
This problem also exists in 0.18.1 version, can anyone let me know how i can resolve this problem
