### ISSUE TITLE
Unable to get MasterEditionData type

### ISSUE THREAD

**Issue by sofinico** [metaplex-foundation/js#287]
Hi! I cannot find a method to get `MasterEditionData` from Master Edition Address or Mint. I do am able to get `MetadataData` using `Metadata.findByMint()` method. Any suggestion?

**Comment by lorisleiva** [comment]
Hi there 👋 

`Metadata.findByMint()` is not valid code from the SDK. You must be referencing the previous SDK that has now been deprecated.
