### ISSUE TITLE
Error on mint: SizedCollectionMetadataMustBeMutable

### ISSUE THREAD

**Issue by JairZijp** [metaplex-foundation/js#294]
Hi all,
When I'm trying a mint on my candymachine it gives me the following error back:
`SizedCollectionMetadataMustBeMutable. Error Number: 6050. Error Message: Setting a sized collection requires the collection metadata to be mutable..`

Even though the collection of the candy machine is mutable, as can be seen here: [https://explorer.solana.com/address/GK1Z94uSKcTCsiUVan1UvuvVfAQKD3XiDx6i6UF4vDvG?cluster=devnet](https://explorer.solana.com/address/GK1Z94uSKcTCsiUVan1UvuvVfAQKD3XiDx6i6UF4vDvG?cluster=devnet)

When I'm minting with the sugar CLI it does work correctly.
Does anyone have any idea what goes wrong here?

**Comment by JairZijp** [comment]
Was fixed by updating to the `next` version: `0.13.0-0`

**Comment by lorisleiva** [comment]
Hi there 👋 What version were you using before?

The `next` tag has actually not been used for a while and is now behind the `latest` tag so I wouldn't recommend using it.

**Comment by JairZijp** [comment]
Hi! I believe I was using the latest. After updating @solana/web3.js it now seems to work also with the `latest` version. So I'll use that 😄 
Thanks!
