### ISSUE TITLE
nft.json is null 

### ISSUE THREAD

**Issue by haris-aqeel** [metaplex-foundation/js#302]
Code Example:
![image](https://user-images.githubusercontent.com/56465230/191609053-acee60cb-0013-488b-8f20-c8db40482e25.png)

I am fetching all NFTS by Owner, but every NFT I receive contains jsonLoaded false and json as null.
![image](https://user-images.githubusercontent.com/56465230/191608900-3274f177-f31e-4c03-964e-a05130515a15.png)

I checked the URL. All of the URLs are valid and contain all information that I need. I want to get the image of NFT. Though the URL is already there then I will have to make a second API call to the URL which I don't want to. 

![image](https://user-images.githubusercontent.com/56465230/191609937-df7cc9ee-d848-4ae8-9a00-1acbc1b923a8.png)

Could anybody tell, how I can get this json loaded true and json containing data atlease image URL in it directly?  Thanks

**Comment by lorisleiva** [comment]
Hi there 👋 

If you read [this entire section](https://github.com/metaplex-foundation/js#findallbymintlist), you should understand why this is happening and what you can do to load the JSON metadata on the next section.

I hope this helps.
