### ISSUE TITLE
Candy Machine validation fails because the value of "now()" is the initial epoch in 1970

### ISSUE THREAD

**Issue by kevinfaveri** [metaplex-foundation/js#306]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@metaplex-foundation/js@0.15.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@metaplex-foundation/js/dist/esm/plugins/candyMachineModule/asserts.mjs b/node_modules/@metaplex-foundation/js/dist/esm/plugins/candyMachineModule/asserts.mjs
index 4c36041..7387100 100644
--- a/node_modules/@metaplex-foundation/js/dist/esm/plugins/candyMachineModule/asserts.mjs
+++ b/node_modules/@metaplex-foundation/js/dist/esm/plugins/candyMachineModule/asserts.mjs
@@ -49,7 +49,7 @@ const assertCandyMachineIsLive = candyMachine => {
 
   const liveDate = candyMachine.goLiveDate;
 
-  if (!liveDate || liveDate.gte(now())) {
+  if (!liveDate || new Date(liveDate.toNumber()) > new Date(Date.now())) {
     throw new CandyMachineNotLiveError(liveDate);
   }
 };
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

---

Didnt go beyond fixing on my side to get to know why now is returning an epoch from 1970, but tested this scenario happens when using the Glow or Phantom wallets for a code like this one:
```
const mintResult = await metaplex
        .use(walletAdapterIdentity(wallet))
        .candyMachines()
        .mint({ 
          candyMachine, 
        })
        .run()
        .catch((e) => {
          console.error(e);
          return null;
        });
```

**Comment by lorisleiva** [comment]
Hi there 👋 

Thanks for raising this! I've made a PR that should hopefully fix this. I'll publish this today as version `0.16.0`. Feel free to ask me to reopen if that did not fix your issue.
