### ISSUE TITLE
Candy Machine Module mint function fails to create a valid transaction while in production

### ISSUE THREAD

**Issue by kevinfaveri** [metaplex-foundation/js#307]
Given the code
```
 const mintResult = await metaplex
        .use(walletAdapterIdentity(wallet))
        .candyMachines()
        .mint({ 
          candyMachine, 
        })
        .catch((e) => {
          console.error(e);
          return null;
        });
```
with a valid candy machine, the NextJS production bundle is not able to generate a valid transaction when this function is called, thus you can't submit it:
![Screen Shot 2022-09-23 at 20 00 41](https://user-images.githubusercontent.com/18222497/192067410-ed8dcf19-7cd6-4c62-9575-ab2e4bdbb5b5.png)

This is the same code in development environment bundle using NextJS:
![Screen Shot 2022-09-23 at 20 01 07](https://user-images.githubusercontent.com/18222497/192067444-7e2c1496-14d6-44cd-9a60-f185edadd0a4.png)

**Comment by kevinfaveri** [comment]
This happens with both cjs and mjs bundles

**Comment by kevinfaveri** [comment]
Confirmed it only happens with "swcMinify" options enabled on NextJS latest

**Comment by kevinfaveri** [comment]
Seems like. this swcMinifier from Vercel has a lot of problems in other libraries as well: https://github.com/chartjs/Chart.js/issues/10673

**Comment by lorisleiva** [comment]
Hi there 👋 

Thanks for raising this!

Unfortunately, I'm going to close this as I don't have the resource to add support for this swcMinify option right now.

Thank you for your understanding.
