### ISSUE TITLE
NFT Metadata returning CORS error

### ISSUE THREAD

**Issue by haris-aqeel** [metaplex-foundation/js#309]
![image](https://user-images.githubusercontent.com/56465230/192211659-b1428e4d-55ac-40ca-9ec0-3b2bc7810bbc.png)
As shown in the image, first I am fetching all of the NFTs and then loading JSON using the load metadata function. 

![image](https://user-images.githubusercontent.com/56465230/192212166-447f6208-32e5-4c6b-9b83-d7141926b4b5.png)

As you can see that the on the second index of the array the JSON still is null. 

The problem I am facing is that call to one of the NFT JSON metadata returns a CORS error. Is there a way to handle this error from the front end? I am using NEXTjs.

**Comment by haris-aqeel** [comment]
When I am pasting that failed to fetch ethernetworkapplied.net............ on the browser, it gives me nft metadata without any issue. Is there any solution to deal with it if I am not willing to use backend API for NEXT JS?

**Comment by haris-aqeel** [comment]
If I use NEXTjs API and use this function on the backend, then I need to pass it mx(metaplex) and public key. Let me know how this is possible

**Comment by haris-aqeel** [comment]
Best part is if we can do the same using frontend

**Comment by haris-aqeel** [comment]
@steveluscher @thlorenz @samuelvanderwaal

**Comment by steveluscher** [comment]
Hi there! Yours is a question about web development more generally, and you’ll get a much quicker answer over at stackoverflow.com! Can you close this issue please, and repost it there as a question?

Likely, you’re going to have to contact the people who run the server that’s blocking you, and ask for an exemption for your domain.

**Comment by haris-aqeel** [comment]
@thlorenz Thanks for your reply! But it does not even work with mode no-cors.

https://ethnetworkapplied.net/info-metadata.json?q=xxxxxxxxxxxxxxxxxxxxxx

![image](https://user-images.githubusercontent.com/56465230/192325406-cfbf585d-37a4-4f0b-b013-c59a55f95a49.png)


When I open this in the browser, it works without any issues. Similarly, if I use postman or backend it works without any CORS issue. I can only use now backend in NEXT js to carry this request but I am not sure how would I be able to pass the metaplex and how to maintain the state if the wallet is disconnected.

**Comment by steveluscher** [comment]
That's consistent with how CORS is applied.

We don't not want your problem fixed, we're just saying that the issue tracker of `metaplex-foundation/js` is the wrong place to get help for your webserver configuration issue. This issue tracker is for bugs relating to the Metaplex JavaScript libraries. You'll get _much_ faster help over at stackoverflow.com from web technologists who can give you targeted advice.

**Comment by haris-aqeel** [comment]
Okay thanks
