### ISSUE TITLE
Error while mint NFT on Solana with Metaplex

### ISSUE THREAD

**Issue by shiningsea0415** [metaplex-foundation/js#310]
My Code is:
const wallet = useWallet();
const connection = new Connection(clusterApiUrl("testnet"));
const metaplex = Metaplex.make(connection)
    .use(walletAdapterIdentity(wallet))
    .use(bundlrStorage());

const mint = async () => {
    const { nft } = await metaplex
      .nfts()
      .create({
        uri: "http://res.cloudinary.com/dmzpebj2g/image/upload/v1664109071/assets/avatars/l43lcylxscgxuux3cbbz.jpg",
        name: "My NFT",
        sellerFeeBasisPoints: 500
      })
      .run();
}

My env:
next@12.2.0
react@17.0.2
react-dom@17.0.2
@metaplex-foundation/js@0.15.0
@metaplex-foundation/mpl-token-metadata@2.2.4
@solana/web3.js@1.63.1

MetaplexError: TokenMetadataProgram > Unknown Program Error
>> Source: Program > TokenMetadataProgram [metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s]
>> Problem: The program [TokenMetadataProgram] at address [metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s] raised an error that is not recognized by the programs registered by the SDK.
>> Solution: Unfortunately, you will need to check the unparsed error below to investigate what went wrong. To get more helpful error messages, ensure the program that failed is registered by the SDK and provides an "errorResolver" method.

Caused By: Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 4: Failed to serialize or deserialize account data: Unknown

[ Logs: Program 11111111111111111111111111111111 invoke [1] |$> Program 11111111111111111111111111111111 success |$> Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1] |$> Program log: Instruction: InitializeMint |$> Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2967 of 1200000 compute units |$> Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success |$> Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL invoke [1] |$> Program log: Create |$> Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2] |$> Program log: Instruction: GetAccountDataSize |$> Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1622 of 1191523 compute units |$> Program return: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA pQAAAAAAAAA= |$> Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success |$> Program 11111111111111111111111111111111 invoke [2] |$> Program 11111111111111111111111111111111 success |$> Program log: Initialize the associated token account |$> Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2] |$> Program log: Instruction: InitializeImmutableOwner |$> Program log: Please upgrade to SPL Token 2022 for immutable owner support |$> Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1405 of 1185033 compute units |$> Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success |$> Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2] |$> Program log: Instruction: InitializeAccount3 |$> Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 4241 of 1181153 compute units |$> Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success |$> Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL consumed 20438 of 1197033 compute units |$> Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL success |$> Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1] |$> Program log: Instruction: MintTo |$> Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 4536 of 1176595 compute units |$> Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success |$> Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s invoke [1] |$> Program log: Error: BorshIoError |$> Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s consumed 3004 of 1172059 compute units |$> Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s failed: Failed to serialize or deserialize account data: Unknown ]

I don't know how to resolve this error.
And uploadMetadata() and findByMint() calls also not working.

**Comment by ninnjak** [comment]
This is because you're trying to run on `testnet` which doesn't have the Metaplex programs loaded. Easiest way of testing is to use `devnet`.

```typescript
const connection = new Connection(clusterApiUrl("devnet"));
```

Otherwise I believe you will need to look  into `amman` to run local validator: 
https://github.com/metaplex-foundation/js/issues/267

**Comment by shiningsea0415** [comment]
and Solana devnet is running nowadays. [https://api.devnet.solana.com/](url)
As I see it, testnet is running. [https://api.devnet.solana.com/](url)

**Comment by lorisleiva** [comment]
Hi there 👋 

Thanks @ninnjak for providing the solution to this issue.

@shiningsea0415, please open new issues when you get a different error to make it easier for anyone to search through GitHub issues.

Your latest error message is due to the fact that some examples in the `js-examples` repository have not been updated to use the latest SDK version. We're working on upgrading them right now.

Thank you for your understanding.

**Comment by shiningsea0415** [comment]
Hi, thank you for your reply.

I can get nfts using following codes.
let myNfts = await metaplex
   .nfts()
   .findAllByOwner(metaplex.identity().publicKey);

but I cannot create NFT using this code.
let { nft } = await metaplex.nfts().create({
    uri: "http://res.cloudinary.com/dmzpebj2g/image/upload/v1664109071/assets/avatars/l43lcylxscgxuux3cbbz.jpg",
    name: "New NFT",
    sellerFeeBasisPoints: 500,
});

I got this error

> MetaplexError: TokenMetadataProgram > Unknown Program Error
> 
> > > Source: Program > TokenMetadataProgram [metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s]
> > > Problem: The program [TokenMetadataProgram] at address [metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s] raised an error that is not recognized by the programs registered by the SDK.
> > > Solution: Unfortunately, you will need to check the unparsed error below to investigate what went wrong. To get more helpful error messages, ensure the program that failed is registered by the SDK and provides an "errorResolver" method.
> 
> Caused By: Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 4: Failed to serialize or deserialize account data: Unknown
> 
> [ Logs: Program 11111111111111111111111111111111 invoke [1] |$> Program 11111111111111111111111111111111 success |$> Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1] |$> Program log: Instruction: InitializeMint |$> Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2967 of 1200000 compute units |$> Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success |$> Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL invoke [1] |$> Program log: Create |$> Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2] |$> Program log: Instruction: GetAccountDataSize |$> Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1622 of 1191523 compute units |$> Program return: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA pQAAAAAAAAA= |$> Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success |$> Program 11111111111111111111111111111111 invoke [2] |$> Program 11111111111111111111111111111111 success |$> Program log: Initialize the associated token account |$> Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2] |$> Program log: Instruction: InitializeImmutableOwner |$> Program log: Please upgrade to SPL Token 2022 for immutable owner support |$> Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1405 of 1185033 compute units |$> Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success |$> Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2] |$> Program log: Instruction: InitializeAccount3 |$> Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 4241 of 1181153 compute units |$> Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success |$> Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL consumed 20438 of 1197033 compute units |$> Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL success |$> Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1] |$> Program log: Instruction: MintTo |$> Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 4536 of 1176595 compute units |$> Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success |$> Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s invoke [1] |$> Program log: Error: BorshIoError |$> Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s consumed 3004 of 1172059 compute units |$> Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s failed: Failed to serialize or deserialize account data: Unknown ]
> 
> I don't know how to resolve this error. And uploadMetadata() and findByMint() calls also not working.
