### ISSUE TITLE
Best practices for storing image files in token metadata program

### ISSUE THREAD

**Issue by Bhaney44** [metaplex-foundation/js#313]
I'm having trouble finding information on best practices for storing image files for the token [metadata program](https://docs.metaplex.com/programs/token-metadata/). In [Issue 748](https://github.com/metaplex-foundation/metaplex-program-library/issues/748), we discovered GitHub is probably not the best method for storing image files for metadata. The general format for the TOKEN_URI file is:

```
{
  "name": "Token Name",
  "symbol": "Token Symbol",
  "description": "Token Description.",
  "image": "Image_Link"
}

```

However, it is difficult to find a compatible storage method for the `image` variable. Ideally an image storage solution would not require any third party dependencies and would be compatible with the token metadata program. Any suggestions or advice would be greatly appreciated.

**Comment by Bhaney44** [comment]
I am using a website called [ImageBam](https://www.imagebam.com/) which is permissionless and free. It allows users to upload and image and it generates a link. I am working toward testing whether this new link will work better than GitHub.

**Comment by samuelvanderwaal** [comment]
https://docs.metaplex.com/resources/storage-providers

**Comment by Bhaney44** [comment]
> https://docs.metaplex.com/resources/storage-providers

Thank you!

**Comment by Bhaney44** [comment]
> https://docs.metaplex.com/resources/storage-providers

@samuelvanderwaal Is there a free method for storage that works? I went through the list and the issue is every option either requires a login or a fee. I've never seen anything like this on any other blockchain. Intuitively, I don't understand this design choice. It would make sense to standardize this so creators could simply upload an image. Any suggestions or guidance would be appreciated. Thanks!
