### ISSUE TITLE
How to update sft metadata

### ISSUE THREAD

**Issue by Bhaney44** [metaplex-foundation/js#314]
One problem I am running into solving [Issue 313](https://github.com/metaplex-foundation/js/issues/313) is that I am intending to update token metadata rather than create it. In [Issue 748](https://github.com/metaplex-foundation/metaplex-program-library/issues/748) we created a method for adding token metadata to an asset. The function we used was:

```
const { sft } = await metaplex
  .nfts()
  .createSft({
    name: "TOKEN NAME",
    uri: "URI_LINK",
    sellerFeeBasisPoints: 0,
    useExistingMint: mint
  })
  .run();
```

Here, we used the `createSft` method. However, I am getting an error running the code for a second time. I'm wondering whether there is an `updateSft` method or what the proper process for updating metadata is. I'd appreciate any advice or guidance. Thanks!

**Comment by samuelvanderwaal** [comment]
> Here, we used the `createSft` method. However, I am getting an error running the code for a second time. I'm wondering whether there is an `updateSft` method or what the proper process for updating metadata is. I'd appreciate any advice or guidance. Thanks!

Try looking in the readme for an `update` method.

**Comment by Bhaney44** [comment]
> > Here, we used the `createSft` method. However, I am getting an error running the code for a second time. I'm wondering whether there is an `updateSft` method or what the proper process for updating metadata is. I'd appreciate any advice or guidance. Thanks!
> 
> Try looking in the README for an `update` method.

I found `UpdateMetadataAccountV2` in the [Instructions](https://docs.metaplex.com/programs/token-metadata/instructions) section. So, how would that method be applied?

```
const { sft } = await metaplex
  .nfts()
  .UpdateMetadataAccountV2({
    name: "TOKEN NAME",
    uri: "URI_LINK",
    sellerFeeBasisPoints: 0,
    useExistingMint: mint
  })
  .run();
```
Would this be the correct syntax?  Apologies for the noob question - it's difficult for me to conceptualize how the method is used without an example. Thanks in advance, I appreciate you!

**Comment by samuelvanderwaal** [comment]
Mteaplex has two different sets of JavaScript libraries:

Each program has a low-level one that is autogenerated directly from the Rust code. These are prefixed with `mpl` and can be found in NPM under the @metaplex-foundation such as [mpl-token-metadata](https://www.npmjs.com/package/@metaplex-foundation/mpl-token-metadata) or you can look at the actual JavaScript code in the `JS` directory of the [corresponding program](https://github.com/metaplex-foundation/metaplex-program-library/tree/master/token-metadata/js).

Then there is the Metaplex JS SDK which can also be found [on NPM](https://www.npmjs.com/package/@metaplex-foundation/js) and is the library in this repo. This is a high-level library that ties together the low-level ones in a more user friendly way. Whenever possible you should use the JS SDK and you only need to reach for the low-level libraries when there's not a function available in the JS SDK.

The README I was referencing is the one for [this repo](https://github.com/metaplex-foundation/js#readme), and if you look through it you'll find an `update` method with an example that should be what you need.

**Comment by Bhaney44** [comment]
> this repo

This is great information - thank you, I really appreciate your thoughtful reply. I am getting to work on this now. I found the two examples they look right. I just need to modify them for the case of the `sft` and the specific element to be changed. I will follow up with an update.

**Comment by Bhaney44** [comment]
I ran:

```
const { sft } = await metaplex
    .nfts()
    .update({ 
        uri: "New_URI",
    })
    .run();

```

Error return:

```
(base) SPL_Token % node metadata3.js
file:///Users/SPL_Token/node_modules/@metaplex-foundation/js/dist/esm/plugins/nftModule/operations/updateNft.mjs:121
  const creators = input.creators === undefined ? nftOrSft.creators : input.creators.map(creator => {
                                                           ^

TypeError: Cannot read properties of undefined (reading 'creators')
    at toInstructionData (file:///Users/SPL_Token/node_modules/@metaplex-foundation/js/dist/esm/plugins/nftModule/operations/updateNft.mjs:121:60)
    at updateNftBuilder (file:///Users/SPL_Token/node_modules/@metaplex-foundation/js/dist/esm/plugins/nftModule/operations/updateNft.mjs:57:47)
    at Object.handle (file:///Users/SPL_Token/node_modules/@metaplex-foundation/js/dist/esm/plugins/nftModule/operations/updateNft.mjs:29:21)
    at Task.callback (file:///Users/SPL_Token/node_modules/@metaplex-foundation/js/dist/esm/plugins/operationModule/OperationClient.mjs:40:31)
    at file:///Users/SPL_Token/node_modules/@metaplex-foundation/js/dist/esm/utils/Task.mjs:58:50
    at Disposable.run (file:///Users/SPL_Token/node_modules/@metaplex-foundation/js/dist/esm/utils/Disposable.mjs:22:36)
    at Task.forceRun (file:///Users/SPL_Token/node_modules/@metaplex-foundation/js/dist/esm/utils/Task.mjs:47:23)
    at Task.run (file:///Users/SPL_Token/node_modules/@metaplex-foundation/js/dist/esm/utils/Task.mjs:29:19)
    at file:///Users/SPL_Token/metadata3.js:27:6
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
```

I will continue to read the docs to work on a solution for this. I think the `update` method should work with `sft` the same as it does for `nft`.

**Comment by samuelvanderwaal** [comment]
You're missing the nft parameter:

```javascript
const { nft: updatedNft } = await metaplex
    .nfts()
    .update({ 
        nftOrSft: nft,
        name: "My Updated Name"
    })
    .run();
 ```
 
 I haven't tried this code but I think that should be the NFT object which has the creators, etc. fields. Your probably going to have to chew some glass here, but look at the examples in the README carefully and I think you'll figure it out. Good luck!

**Comment by Bhaney44** [comment]
> const { sft } = await metaplex
>   .nfts()
>   .createSft({
>     name: "TOKEN NAME",
>     uri: "URI_LINK",
>     sellerFeeBasisPoints: 0,
>     useExistingMint: mint
>   })
>   .run();

Are you sure? There was not an `nft` parameter in the create function, it was an `sft` parameter:

```
const { sft } = await metaplex
  .nfts()
  .createSft({
    name: "TOKEN NAME",
    uri: "URI_LINK",
    sellerFeeBasisPoints: 0,
    useExistingMint: mint
  })
  .run();
```

This is the line that looks like the issue:
`nftOrSft: nft,`

I think it should be:

`nftOrSft: sft,`

I've tried both, but I'm getting a reference error I need to sort out.

**Comment by lorisleiva** [comment]
I've just realised the README is out of date for this but the [`update` operation](https://metaplex-foundation.github.io/js/classes/js.NftClient.html#update) no longer returns the NFT or SFT after updating. You need to explicitly fetch that data again. The [`refresh` operation](https://metaplex-foundation.github.io/js/classes/js.NftClient.html#refresh) can help with that.

**Comment by Bhaney44** [comment]
> `refresh` operation

```
sft = await metaplex.nfts().refresh(sft).run();

const { sft } = await metaplex
    .nfts()
    .update({ 
        nftOrSft: sft,
        uri: "URI_LINK",
    })
    .run();
```
I am running the refresh operation as documented:

`sft = await metaplex.nfts().refresh(sft).run();`

But I am getting a reference error.

`ReferenceError: Cannot access 'sft' before initialization`

I am having trouble understand what `sft` is and how it operates. For example, is `sft` an object, function, or an element? I understand it stands for semi-fungible token, but to solve the reference error, I'm wondering if I need to import it from somewhere or define it differently. Any suggestions would be appreciated. Thanks again.

**Comment by lorisleiva** [comment]
You're not calling the operations in the right order and you are override `const` variables.

Have you tried this?

```ts
await metaplex
    .nfts()
    .update({ 
        nftOrSft: sft,
        uri: "URI_LINK",
    })
    .run();

const updatedSft = await metaplex.nfts().refresh(sft).run();
```

**Comment by Bhaney44** [comment]
Yeah - just ran this.

```
sft = await metaplex.nfts().refresh(sft).run();

await metaplex
.nfts()
.update({ 
    nftOrSft: sft,
    uri: "",
})
.run();

const updatedSft = await metaplex.nfts().refresh(sft).run();
```
To get:

`ReferenceError: sft is not defined`

I also ran this.

```
await metaplex
.nfts()
.update({ 
    nftOrSft: sft,
    uri: "",
})
.run();

const updatedSft = await metaplex.nfts().refresh(sft).run();
```
To get:
`ReferenceError: sft is not defined`

I'm still having the same problem in not understanding the `sft` method. I think you're probably right that I am not calling the operations in the right order, and that I'm overwriting `const` variables. I will try some different arrangements and maybe changing to `let` variables. If you have any other suggestions, I sincerely appreciate your help. Thanks!
