### ISSUE TITLE
Error with newly migrated NFT Collection

### ISSUE THREAD

**Issue by Jack-R-Long** [metaplex-foundation/js#318]
Hello,

I just migrated my NFT collection to the new Metaplex certified collection standard using their tool at [link](https://collections.metaplex.com/)

Now when I try and run `.nfts().update()` I get the following error
```
Source: Program > TokenMetadataProgram [metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s]

>> Problem: The program [TokenMetadataProgram] at address [metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s] raised an error of code [101] that translates to "Can't use this function on unsized collection".
```

How can I size the collection?  I would like to be able to update our NFTs again ASAP.

**Comment by lorisleiva** [comment]
Hi there 👋 I know this was raised before #319 but since it has more activity, I'll mark this one as duplicate and close it. Thanks for raising this!
