### ISSUE TITLE
Update method - Can't use this function on unsized collection

### ISSUE THREAD

**Issue by jesign** [metaplex-foundation/js#319]
Hi i'm getting this error when updating an NFT that belongs to an unsized collection: 

key: 'metaplex.errors.program.parsed_program_error',
  title: "TokenMetadataProgram > Can't use this function on unsized collection",
  problem: `The program [TokenMetadataProgram] at address [metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s] raised an error of code [101] that translates to "Can't use this function on unsized collection".`,
  solution: 'Check the error message provided by the program.',
  source: 'program',
  sourceDetails: 'TokenMetadataProgram [metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s]',
  
i used the update method to update. 

const result = await metaplex.nfts().update({
   nftOrSft: nft,
   uri: newUri
}).run();

i also tried to add a `collectionIsSized:  true` in the params. but it still doesn't work. 
how do we update NFTs that belong to unsized collection now?

**Comment by myyellowshoe** [comment]
I wonder if you could use migrateToSizedCollectionNft function to fix this issue?

[migrateToSizedCollectionNft.ts](https://github.com/metaplex-foundation/js/blob/main/packages/js/src/plugins/nftModule/operations/migrateToSizedCollectionNft.ts)

**Comment by Jack-R-Long** [comment]
Same issue here!  I posted on stack exchange https://solana.stackexchange.com/questions/3469/error-with-newly-migrated-certified-nft-collection

**Comment by jesign** [comment]
@myyellowshoe , 
it would make a new error, it says `Cannot verify collection in this instruction. `

**Comment by jesign** [comment]
it seems like unverifying the collection before updating works. but i will have to verify it again. 
is this the expected behaviour?

**Comment by lorisleiva** [comment]
Hi there 👋 

Thank you for raising this. It's a bug, I've been able to reproduce it on a regression test. Fixing this and publishing a new version today (it will have to be a minor jump since `main` contains some small breaking changes for other modules).

**Comment by lorisleiva** [comment]
I will publish this as version `0.16.0` today. Let me know if that didn't fix your issue and I'll reopen it. 🤞

**Comment by devpake** [comment]
I had the same issue prior to `0.16.0`.  I updated yesterday and reapplied verification, it went through ok.

However, today I created a 2nd SFT with the newest update.  I initially set it with no collection.  Then I updated it to point to collection but now can't verify it.  

I also tried creating a new SFT with the collection already defined but same error response.

General outline of steps
```
  await metaplex.nfts().createSft(<sft w/ no collection defined>).run();  // OK
  await metaplex.nfts().update({nftOrSft: token, collection: new PublicKey(collectionAddr)}).run();  // OK
  await metaplex.nfts().verifyCollection({mintAddress: token.pubkey, collectionMintAddr: collection.pubkey}).run()

Error:  
{
   ...
   problem: `The program [TokenMetadataProgram] at address [metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s] raised an error of code [101] that translates to "Can't use this function on unsized collection".`,
   ...
}
```

**Comment by jesign** [comment]
Thank you Loris! i'll check it out.

**Comment by fa8ster** [comment]
![image](https://user-images.githubusercontent.com/1168345/205281135-5b0fcd97-791c-4a4a-8f0e-74922a77f7f6.png)
I tried 
`let address = new web3.PublicKey(
    "Co3XhKHJAefgWYmrZFnVx4GKq5xWBsqfHEuedgEjBvNn"
  );
  let nft = await metaplex.nfts().findByMint({ mintAddress: address });

  let result = await metaplex.nfts().update({
    nftOrSft: nft,
    name: "SAM #9998",
  });`

but the issue seems to be remaining. It's also an unsized MCC.
Using `0.17.6`

**Comment by fa8ster** [comment]
I had to upload a new json and it worked
```
const { uri: newUri } = await metaplex.nfts().uploadMetadata({
    ...nft.json,
    name: "SAM #6665",
  });

  let result = await metaplex.nfts().update({
    nftOrSft: nft,
    name: "SAM #6665",
    uri: newUri,
  });

```
