### ISSUE TITLE
Upgrading to 0.15 storage issues.

### ISSUE THREAD

**Issue by rastrent** [metaplex-foundation/js#320]
It looks like the api has changed around bundlr / storage integration. I upgraded the to the `toMetaplexFile` but wondering what else I'll need to update here.

```
   const cardFile = toMetaplexFile(
      cardImageUrl[0],
      cardData.image.split("images/collections/")[1], 
    );

    const storage = metaplex.storage().driver();
    storage.fund([cardFile]);

```

Offchain Metadata Created successfully at:  undefined
error - unhandledRejection: TypeError: Cannot read properties of undefined (reading 'toString')
    at **amountToBigNumber** (/Users/test/party/node_modules/@metaplex-foundation/js/dist/cjs/plugins/bundlrStorage/BundlrStorageDriver.cjs:225:63)
    at BundlrStorageDriver.fund (/Users/test/party/myproject/node_modules/@metaplex-foundation/js/dist/cjs/plugins/bundlrStorage/BundlrStorageDriver.cjs:106:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by rastrent** [comment]
Happy to update the docs once we nail down whats going on here.

**Comment by rastrent** [comment]
I noticed the funding was happening automagically in upload all so just decided to use that.
```
    const cardFile = toMetaplexFile(
      ImageBuffer,
      'myfilename.png',
    );
    const storage = metaplex.storage().driver();
    const imageUri = await storage.upload(cardFile);

    const offChainMetadata = {
      name: 'test',
      symbol: "test",
      image: imageUri,
      properties: {
        files: [
          {
            uri: imageUri,
            type: "image/png",
          },
        ],
        category: "image",
      },
    };

``

**Comment by lorisleiva** [comment]
Hi there 👋 

Yes, it should fund it properly when passing the files directly to the upload operation.

However, there's a little known issue with this upload operation as it will treat any provided file as a different file (even if it's the same reference). As you're providing the same file twice I just wanted to flag this. This issue is on my todo list.

**Comment by myyellowshoe** [comment]
Yeah not worried to much about that near term, but great to know. Thanks so much for your work on this 👏
