### ISSUE TITLE
Collection Update authority

### ISSUE THREAD

**Issue by myyellowshoe** [metaplex-foundation/js#323]
I'm trying to better understand how to add a new nft into a previously created collection. The prior collection is created with the same wallet that the new one is. But the collection doesn't seam to be getting verified. Do i need to create a seperate keypair thats just for update authority or should the wallet keypair be fine?

What i have now:
```
 const collectionUpdateAuthority = walletKeyPair;
  const collectionNft = await createCollectionNft(mx, {
    updateAuthority: collectionUpdateAuthority,
  });
```

**Comment by lorisleiva** [comment]
Hi there 👋 

You simply need to pass both the collection and the collection authority when creating or updating an NFT.

```ts
const { nft } = await mx
  .nfts()
  .create({
    collection: collectionNft.address,
    collectionAuthority: collectionUpdateAuthority,
    // ...
  })
  .run();
```

I hope this help. 🍀

**Comment by myyellowshoe** [comment]
Ahhh ok this works perfectly now! and looks like I had a variable named wrong as well. Nothing like a couple days away to show you the obvious :D

I really do appreciate all the work on this!
