### ISSUE TITLE
`loadJsonMetadata` option for all NFT module functions

### ISSUE THREAD

**Issue by callensm** [metaplex-foundation/js#328]
Add the `loadJsonMetadata` option to all NFT module search functions instead of just `findByMetadata`.

**Comment by lorisleiva** [comment]
Hi there 👋 Isn't this already the case in the latest version?

**Comment by callensm** [comment]
it is implemented for single item search operations, but `findAllByXXX` multi-item searches do not provide this option.

**Comment by lorisleiva** [comment]
Oh yeah, that's by design. It would really not be performant to load JSON files from unknown URIs for a list of NFT of an unknown length. Instead, you get a `Metadata` model and you can use the `load` operation to fetch them fully as you wish, e.g. as you paginate them.
