### ISSUE TITLE
Candy Machine Mint fails w/Bot Tax exception when confirmation != finalized

### ISSUE THREAD

**Issue by cosimo-rip** [metaplex-foundation/js#330]
We noticed our minting process took a bit longer than desired, and changed our mint call to wait for confirmed rather than finalized transactions:
```
const mintResult = await metaplex
      .candyMachines()
      .mint({
        candyMachine: candyMachine,
        confirmOptions: { commitment: "confirmed" },
      })
      .run();
```

Unfortunately, this leads to a bot tax exception, because the mint method tries to find the minted NFT immediately after the first transaction is completed:
https://github.com/metaplex-foundation/js/blob/4de8d828723dfa23f6486b6a0a6fb7856998952c/packages/js/src/plugins/candyMachineV2Module/operations/mintCandyMachineV2.ts#L217-L230

I think this check should only be enforced for finalized commitments.

**Comment by skeletoncrewrip** [comment]
Makes sense - thanks for outlining the tx builder option too. Good to close!
