### ISSUE TITLE
`metaplex.nfts().update(nft, onChainData);` works, but returns an error

### ISSUE THREAD

**Issue by Jack-R-Long** [metaplex-foundation/js#331]
Updating NFT name.  The change works but for some reason it throws an error.  Here is the code

```
      try {
        await metaplex
        .nfts()
        .update({
          nftOrSft: nft,
          name: fullName,
          uri: newUri,
        })
        .run();
      } catch(e) {
        console.error(response);
      }  
```

Very strange.  Any help is greatly appreciated!

**Comment by lorisleiva** [comment]
Hi there 👋 

Which error do you get?

This might not be it but I think there's a typo in the code you shared:

```ts
catch(e) {
  console.error(response);
  //            -------- response is not defined.
}
```

**Comment by Jack-R-Long** [comment]
Ooop good catch.  So I am getting a timeout error.  Tx could not confirm within 30 seconds.
