### ISSUE TITLE
Buffer is not defined error

### ISSUE THREAD

**Issue by cryptoHaHa** [metaplex-foundation/js#338]
I am using react js framework, not tsx.
In there, I imported Metaplex and added below code line.
`const metaplex = new Metaplex(connection)`
Then, I got js error "Uncaught ReferenceError: Buffer is not defined". How can I solve this problem?

**Comment by gesielrosa** [comment]
Buffer is not a browser feature. You need to install `buffer` package.
To read more: [here](https://stackoverflow.com/questions/48432524/cant-find-variable-buffer)
