### ISSUE TITLE
@metaplex-foudation/js is creating an error (class extends value undefined is not a constructor or null ) 

### ISSUE THREAD

**Issue by KhalilElati** [metaplex-foundation/js#343]
![Capture](https://user-images.githubusercontent.com/59478433/194712438-ef7d54ad-d3a5-4315-b463-e91b97abeddf.PNG)

**Comment by KartikSoneji** [comment]
Hi

Can you please provide some more details?
Like what code you are trying to run, what framework you are using (React/Vanilla/Vue/etc)

**Comment by KhalilElati** [comment]
I am using a react app, and this is the piece of code that's triggering the problem 
const metaplex = Metaplex.make(connection)
everything works except this line,

**Comment by KartikSoneji** [comment]
Would you mind creating a repository with the source code for that app?

**Comment by KartikSoneji** [comment]
Hi @samia-invozone
If you are facing the same issue can you please provide a minimum reproducible example, or the steps you took to setup the project so I can replicate it?

**Comment by samia-invozone** [comment]
@KartikSoneji Actually, It's a private project. If I share package.json can you figure it out by installing node_modules in your react app?

**Comment by lorisleiva** [comment]
@samia-invozone Can you please create a new public repository that contains the minimum amount of code to reproduce this error?

Also, did you follow the polyfill steps mentioned in the [js-examples repository](https://github.com/metaplex-foundation/js-examples)?

**Comment by KhalilElati** [comment]
Hey, you can update the metaplex/js to 0.18.1 it works fine, it's not a solution but it fixes the issue.

**Comment by lorisleiva** [comment]
I'm confused, version 0.18.1 does not exist on this SDK.

**Comment by KartikSoneji** [comment]
Hi @aeaa1998 
Is there any particular reason you are polyfilling the crypto module?

**Comment by surenzeroonelabs** [comment]
We had the similar issue. The culprit for us was `@bundlr-network/client`. To solve it we forked and removed `js-plugin-nft-storage` entirely. Along with that we made sure there is no peer dependency to `@bundlr-network/client`.

This is the issue only for browser builds for nodejs it runs fine.

**Comment by surenzeroonelabs** [comment]
Upon further investigation, we found that the value of `Account` is null or undefined in this line https://github.com/near/near-api-js/blob/37ca2222e7afda3b77929d695b9d84bba21b418e/packages/near-api-js/src/account_multisig.ts#L51

`near-api-js` is a dependency to `@bundlr-network/client`. 

The local build works but the build from our pipeline at `netlify` fails.

**Comment by aeaa1998** [comment]
@KartikSoneji  Hi! Sorry for the late reply.
To be honest that was just copied it from the JS example of Vite configuration.

I migrated to Webpack 5 and updated the @metaplex-foundation/js to v0.17.1 and everything worked fine again.

**Comment by KartikSoneji** [comment]
Might be resolved by metaplex-foundation/js-examples#30
