### ISSUE TITLE
`0.17.0` does not work with browsers (CRA5)

### ISSUE THREAD

**Issue by acheroncrypto** [metaplex-foundation/js#346]
For easy reproducability, upgrade to version `0.17.0` in the example repo: https://github.com/metaplex-foundation/js-examples/tree/main/getting-started-react-cra5 and try to fetch a v3 account:
```ts
await metaplex.candyMachines().findByAddress({
  address,
});
```

This throws an error: `(0 , _types_BigNumber_mjs__WEBPACK_IMPORTED_MODULE_3__.toBigNumber)(...).toBuffer is not a function`

**Comment by lorisleiva** [comment]
Thanks again for this! The fix has been published in version `0.17.1`. 🚀
