### ISSUE TITLE
How to implement non-transferable NFT using Metaplex JS SDK?

### ISSUE THREAD

**Issue by shiningsea0415** [metaplex-foundation/js#350]
Hi
I am trying to make my mint NFT as a non-transferable token(soul bound token).
But I am not sure how to implement this using metaplex/js SDK.
Please help me.

**Comment by tjkyner** [comment]
Hello! 

I believe you're looking for the `freezeDelegatedNft` method ([see docs](https://metaplex-foundation.github.io/js/classes/js.NftClient.html#freezeDelegatedNft)). Something like the following should work:

```typescript
await metaplex
    .nfts()
    .freezeDelegatedNft({ mintAddress, delegateAuthority })
```

For a good overview on the intricacies of the instruction and the accounts layout, see [this post](https://github.com/metaplex-foundation/metaplex-program-library/issues/470#issuecomment-1132700105) from @lorisleiva.

Hope this helps!
