### ISSUE TITLE
Signature verification failed when creating Nft

### ISSUE THREAD

**Issue by cmitjans-at-wiris** [metaplex-foundation/js#352]
I'm trying to create a simple nft using Metaplex Foundation library in a Nuxt 3 project.

The code I'm using:

```typescript
import { Metaplex, walletAdapterIdentity } from '@metaplex-foundation/js';
import {
  clusterApiUrl,
  Connection,
} from '@solana/web3.js';
import { useWallet } from 'solana-wallets-vue';

const connection = new Connection(clusterApiUrl('devnet'));
const { wallet } = useWallet();

const metaplex = new Metaplex(connection);
metaplex.use(walletAdapterIdentity(wallet.value));

const output = await metaplex.nfts().create({
  name: 'My NFT',
  sellerFeeBasisPoints: 500, // Represents 5.00%.
  uri: 'https://arweave.net/123',
});
```

I'm getting the following error:

```
Uncaught (in promise) Error: Signature verification failed
```

Am I missing something?

**Comment by cmitjans-at-wiris** [comment]
I'm also getting this ugly warning with Brave Wallet before signing the transaction (which fails with the error described).

<img width="875" alt="Screenshot 2022-10-16 at 15 29 26" src="https://user-images.githubusercontent.com/79908984/196038131-e24fb2e8-3224-4c60-8b28-9485c8298c3f.png">

With Phantom Wallet, I'm getting this "Transaction Expired" error message:
<img width="826" alt="Screenshot 2022-10-16 at 15 30 09" src="https://user-images.githubusercontent.com/79908984/196038174-8424899b-3811-44ff-85f2-300969f77d1e.png">

**Comment by lorisleiva** [comment]
That's an issue with the Vue library for wallet adapters. I'm working on a new version as we speak which supports the new requirements of web3.js.

Closing this since it's not related to this package.

**Comment by aerctic** [comment]
Having the exact same `Signature verification` issue with react/nextjs.

**Comment by lorisleiva** [comment]
@aerctic Are you using Phantom? If so, can you make sure that the Network used in the Phantom settings matches what your dApp is requesting?

**Comment by aerctic** [comment]
@lorisleiva I forgot to run `npm update` 😬 works perfectly now, thanks for the reply! :D
