### ISSUE TITLE
SDK support for the Fixed Price Sale contract

### ISSUE THREAD

**Issue by serejke** [metaplex-foundation/js#369]
Hello!
I'm extensively using that metaplex JS library for NFT minting/exploring. That's awesomely convenient!

Now I'm researching on the best smart-contract for implementing NFT sales. At the moment we're going to have only the sales of a fixed price.
I used to work with AuctionHouse and it definitely has all the features that we need, and even much more than that. The downside is its complexity.

I've found there is a Fixed Price Sale contract (https://docs.metaplex.com/programs/fixed-price-sale/).
Unfortunately, it's very poorly documented. It seems to be an outdated contract. 

This SDK also does not have support for that.

I'm wondering whether it's a deprecated contract and I would rather learn AuctionHouse, or there is a good use case for the Fixed Price Sale? (BTW Any links to the examples using it will be much appreciated!)

**Comment by gesielrosa** [comment]
Hello.
Isn't Direct buy from Auction House a option to you? i'm using it.
In Auction House, you can list the assets with price, after that, buy using direct buy operation.
