### ISSUE TITLE
metaplex.nfts().create() Primary Sale Happened

### ISSUE THREAD

**Issue by indynov** [metaplex-foundation/js#382]
I was looking at the options here and noticed Primary Sale Happened isn't listed https://metaplex-foundation.github.io/js/types/js.CreateNftInput.html

https://docs.metaplex.com/programs/token-metadata/accounts

Could you offer this as a configuration option for metaplex.nfts().create()?

**Comment by lorisleiva** [comment]
Hi there 👋 

The Token Metadata program does not offer the ability to set `primarySaleHappened` to `true` when creating the Metadata account of an NFT. We could bundle an update instruction in there as well but this might not be what most users need when creating NFTs.

My suggestion is to use the `metaplex.nfts().update()` operation to flip the `primarySaleHappened` boolean.

You could even do that within the same transaction using transaction builders like so:

```ts
const transactionBuilder = await metaplex.nfts().builders().create(...);
transactionBuilder.add(metaplex.nfts().builders().update(...));
await metaplex.rpc().sendAndConfirmTransaction(transactionBuilder);
```
