### ISSUE TITLE
Issue with metaplex.nfts().findAllByCreator() on Alchemy

### ISSUE THREAD

**Issue by indynov** [metaplex-foundation/js#386]
With this script pastebin.com/raw/9Hh23x2z it puts the output in a file called test_results.txt, if you run it on Alchemy you will see 0 results in it, if you run it on Quicknode you will see around 5000 results - the results of everything in the collection "Mystopians"

**Comment by KartikSoneji** [comment]
Can you please confirm that this is not an issue with Alchemy?
Maybe they are blocking the `getProgramAccounts` method on their rpc since it is quite a resource-intensive call.
