### ISSUE TITLE
metaplex.nfts().findAllByCreator() suggestion

### ISSUE THREAD

**Issue by indynov** [metaplex-foundation/js#393]
It takes a long time for the command to process often. Would be nice to have updates to the console on progress. Every 100 NFTs it could say
"findAllByCreator in progress, found so far: 100 NFTs"
"findAllByCreator in progress, found so far: 200 NFTs"
And so on, would be very easy to implement but give some user feedback. It's possible that by default commands could give more user feedback but you can toggle a setting such as metaplex.nfts().logging(false) or something like that if you want to turn the logs off or on

**Comment by KartikSoneji** [comment]
Both `findAllByCreator()` and `findAllByUpdateAuthority()` make only a single rpc call to the `getProgramAccounts` method.
The nfts are returned all at once, not incrementally so there is no good way to implement an accurate progress meter.
The time taken by the rpc to return the accounts varies greatly by the provider, which node is handling the request and how active the network is at the moment.
