### ISSUE TITLE
Cannot get my auctionHouse when I set auctioneerAuthority

### ISSUE THREAD

**Issue by rockdev055** [metaplex-foundation/js#397]
I have an issue when I set auctioneerAuthority to get auctionHouse. How can I fix this issue?

```
import pack from "@solana/web3.js";
const { Connection, clusterApiUrl, PublicKey } = pack
import { Metaplex } from "@metaplex-foundation/js";

async function test() {
  const connection = new Connection(clusterApiUrl("devnet"));
  const metaplex = new Metaplex(connection);

  const [ auctioneerAuthority ] = await PublicKey.findProgramAddress(
    [Buffer.from("auctioneer"), (new PublicKey("DJMykZPWa1xRVReukrKsarcFedbD8NnTUm8d1CEERCq9")).toBuffer()],
    new PublicKey("neer8g6yJq2mQM6KbnViEDAD4gr3gRZyMMf4F2p3MEh")
  );

  console.log(auctioneerAuthority.toString())

  const auctionHouse = await metaplex.auctionHouse().findByAddress(
    {
      address: new PublicKey("DJMykZPWa1xRVReukrKsarcFedbD8NnTUm8d1CEERCq9"), 
      auctioneerAuthority: auctioneerAuthority
    }
  )

  console.log(auctionHouse)

  return auctionHouse
}

await test()
```
![image](https://user-images.githubusercontent.com/30362975/199608183-2e130a76-791a-40e0-9cfd-02ab0c8fd596.png)

**Comment by lorisleiva** [comment]
Hi there 👋 

I think this is because the Auctioneer account data has changed relatively recently on the program and the SDK is not up-to-date on Auctioneer yet.

It's on my To-Do list but in the meantime, I recommend you use the autogenerated JS libraries as they will be up-to-date.

**Comment by rockdev055** [comment]
Hi @lorisleiva,

Thank you for your response.

Can you please let me know how to go back? I just wanted to remove the Auctioneer delegate from the Auction House.

Is it possible?
