### ISSUE TITLE
metaplex.nfts().findAllByOwner() doesn't work

### ISSUE THREAD

**Issue by ilanoh** [metaplex-foundation/js#400]
Hello, interesting enough, but not expected, not matter which wallet is provided to this call:

user = new PublicKey("...")
metaplex.nfts().findAllByOwner({ owner: metaplex.identity().user }).run()

Metaplex returns always the list of NFTs of a fixed wallet, that was never provided in the first place.
I input 'x' different wallet, I always receive the NFTs list of a wallet 'y', that I don't own, and that I have not tested.

**Comment by gesielrosa** [comment]
Try it

```javascript
const ownerPublicKey = new PublicKey("...") // owner public key
const myNfts = await metaplex.nfts().findAllByOwner({
    owner: ownerPublicKey
});
```

**Comment by KartikSoneji** [comment]
Hi @ilanoh 
Can you please provide a running example that we can use to debug this?
