### ISSUE TITLE
TokenLendingError#AlreadyInitialized: Account is already initialized

### ISSUE THREAD

**Issue by leonidstrelok** [metaplex-foundation/js#405]
Executing the code:
const createAuction = async (
  nftAddress: PublicKey
): Promise<CreateAuctionHouseOutput> => {
  const auction = await metaplex.auctionHouse().create(
    {
      sellerFeeBasisPoints: 500,
      requiresSignOff: true,
      auctioneerScopes: [0, 1, 2, 3, 4, 5, 6],
      authority: metaplex.identity().publicKey,
      treasuryMint: nftAddress,
      canChangeSalePrice: true,
    },
    { confirmOptions: { skipPreflight: true } }
  );
  console.log("AUCTION: ", auction);
  console.log("_____________________________________________");
  console.log("ADDRESS 1: ", auction.auctionHouse.address.toBase58());
  console.log("ADDRESS 2: ", auction.auctionHouseAddress.toBase58());
  
  console.log("_____________________________________________");
  
  return auction;
};
Then: 
const createListing = async (auction: AuctionHouse, mintAccount: any) => {
  console.log("START LISTING: ", mintAccount);

  const listing = await metaplex.auctionHouse().list(
    {
      auctionHouse: auction,
      mintAccount: mintAccount,
    }
  );
  console.log("LISTING: ", listing);
};

And the error comes out: 
Caused By: TokenLendingError#AlreadyInitialized: Account is already initialized"   

at RpcClient.parseProgramError (C:\Users\SUMBAR\Visual Studio Code Project\mint-fungible-spl\node_modules\@metaplex-foundation\js\src\plugins\rpcModule\RpcClient.ts:366:9)
    at RpcClient.sendTransaction (C:\Users\SUMBAR\Visual Studio Code Project\mint-fungible-spl\node_modules\@metaplex-foundation\js\src\plugins\rpcModule\RpcClient.ts:128:18)
    ... 4 lines matching cause stack trace ...
    at async Disposable.run (C:\Users\SUMBAR\Visual Studio Code Project\mint-fungible-spl\node_modules\@metaplex-foundation\js\src\utils\Disposable.ts:33:14) {
  key: 'metaplex.errors.program.parsed_program_error',
  title: 'AuctionHouseProgram > Account is already initialized"',
  problem: 'The program [AuctionHouseProgram] at address [hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk] raised an error of code [1] that translates to "Account is already initialized"".',
  solution: 'Check the error message provided by the program.',
  source: 'program',
  sourceDetails: 'AuctionHouseProgram [hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk]',

**Comment by gesielrosa** [comment]
`treasuryMint` is not the NFT address.

![Screenshot 2022-11-14 at 11 47 35](https://user-images.githubusercontent.com/40439982/201689946-5ed713b7-180f-4134-bf86-41157c7e0ac0.png)

**Comment by leonidstrelok** [comment]
@gesielrosa And can you please tell me in what order you need to create an auction

**Comment by top1st** [comment]
This problem is not solve yet for me also.
