### ISSUE TITLE
Migrating "old" Auction code

### ISSUE THREAD

**Issue by gxxcastillo** [metaplex-foundation/js#407]
Hi, a while back I wrote a client for creating auctions (w/ a reserve price, tick size, etc) using a DAO where all bidders get a participation NFT.  When I recently went to update this client I found that a lot of the underlying code it depends on has changed significantly.

Currently, I'm leaning on packages like `@solana/web3.js`, `@metaplex-foundation/mpl-core`, `@metaplex-foundation/mpl-auction`, `@metaplex-foundation/mpl-token-vault`, `@metaplex-foundation/mpl-token-metadata`, `@metaplex-foundation/mpl-metaplex`, etc., in order to create a store, set creators, create a vault, place NFTs into the vault, create an auction, create an auction manager, validate the auction, and finally upon approval of the DAO proposal, start the auction and have all funds go directly to the DAO.

I don't see code to handle this type of flow with `@metaplex-foundation/js` at the moment, are there plans to support it? I'm not familiar with Auction House yet, will I need to use that instead of what I'm doing now?

**Comment by KartikSoneji** [comment]
I'm not too familiar with auction house but does https://github.com/metaplex-foundation/js/pull/366 help?

**Comment by lorisleiva** [comment]
Hey @gxxcastillo, yes the new Auction House program basically replaces the need for Auctions and Token Vault. There is an Auction House module of this JS SDK but it's not 100% finished yet and therefore not quite ready to be documented I'm afraid.
