### ISSUE TITLE
Timed Auction

### ISSUE THREAD

**Issue by leonidstrelok** [metaplex-foundation/js#423]
Hello everyone, can you tell me how you can create an English auction, with a timer set for a certain time and a price increase. Thank you very much for the answers in advance

**Comment by lorisleiva** [comment]
Hi there 👋 

I'm afraid the JS SDK does not support the "Timed Auction" auctioneer program yet.

I will mark this issue as a question in case you'd like to move this over to SO. Thank you for understanding.

**Comment by leonidstrelok** [comment]
@lorisleiva Well, then how do I make a temporary auction?

**Comment by leonidstrelok** [comment]
@lorisleiva
 1) I have one more question regarding the auction, in case I canceled the bid, how can I get the money back.
2) I canceled the listing, but the bid has already been created, how to return the money to the owner

**Comment by lorisleiva** [comment]
I think this might help: https://docs.metaplex.com/programs/auction-house/managing-buyer-account#withdraw-funds
