### ISSUE TITLE
Proper output type for `findBids` operation

### ISSUE THREAD

**Issue by KartikSoneji** [metaplex-foundation/js#458]
The `findBids` operation should have an output type of `LazyBid[]` instead of `(LazyBid | Bid)[]` since it only returns lazy bids.

https://github.com/metaplex-foundation/js/blob/a14a0920c62fbc140c53675d2d9d519a7a737bff/packages/js/src/plugins/auctionHouseModule/operations/findBids.ts#L80

https://github.com/metaplex-foundation/js/blob/a14a0920c62fbc140c53675d2d9d519a7a737bff/packages/js/src/plugins/auctionHouseModule/operations/findBids.ts#L120

**Comment by lorisleiva** [comment]
Hi there, this was a design decision to allow other operation handlers to return more data in one go. E.g. this would allow indexers to provide the full Bid whilst allowing users to keep the same API.
