### ISSUE TITLE
Any way to make the { payer } be a publicKey

### ISSUE THREAD

**Issue by kevinfaveri** [metaplex-foundation/js#478]
I found a workaround for this already, but my use case is the following: want to use the transaction builder to generate the txn on the BE and then send to the FE the partially signed txn so that the payer will be the public key on the FE.

Currently, transaction builder expects a payer of type Signer, as it does sign on itself. Would be cool to have a feature where you can just build the transaction, and then set the payer, but don't sign the transaction in advance inside the builder algorithm.

**Comment by KartikSoneji** [comment]
For now, I have been using this:

```js
 let metaplex = Metaplex.make(connection)
      .use(walletAdapterIdentity({
        publicKey: new PublicKey("..."),
        signTransaction: async (tx) => tx
      }));
```

**Comment by kevinfaveri** [comment]
> For now, I have been using this:
> 
> ```js
>  let metaplex = Metaplex.make(connection)
>       .use(walletAdapterIdentity({
>         publicKey: new PublicKey("..."),
>         signTransaction: async (tx) => tx
>       }));
> ```

Yep. I have been doing the same. Thanks for sharing tho! Would be nice to have the library supporting this use case tho.

**Comment by KartikSoneji** [comment]
Actually, just found this
https://metaplex-foundation.github.io/js/functions/js.guestIdentity.html

**Comment by lorisleiva** [comment]
Hi there, using a "noop" signer is expected here to ensure proper typing on the SDK.

I've taken that into consideration in the [new JS Solana client framework](https://github.com/metaplex-foundation/umi) I'm building by providing [a `createNoopSigner` helper method](https://github.com/metaplex-foundation/umi/blob/233efd719fcd6ed003d69d4217a62d7845a91177/packages/umi-core/src/Signer.ts#L70).
