### ISSUE TITLE
`animation_url` field discrepancy with docs and `JsonMetadata` type

### ISSUE THREAD

**Issue by nicholas-ewasiuk** [metaplex-foundation/js#500]
Token Metadata standard documentation https://docs.metaplex.com/programs/token-metadata/token-standard shows an `animation_url` field. The `JsonMetadata` type is missing the `animation_url` field. https://github.com/metaplex-foundation/js/blob/main/packages/js/src/plugins/nftModule/models/JsonMetadata.ts

Which is the correct info? Should the `animation_url` be included in that `JsonMetadata` type?

**Comment by lorisleiva** [comment]
Hi there, `animation_url` is a valid optional attribute of the JSON metadata. It is just missing from the `JsonMetadata` type.

**Comment by nicholas-ewasiuk** [comment]
Okay, thanks for the response Loris. Can I submit a PR to add it to the `JsonMetadata` type?

**Comment by lorisleiva** [comment]
Yes, that would be helpful thank you!

**Comment by lorisleiva** [comment]
Fixed by #502
