### ISSUE TITLE
Burn Nft with name in Mainnet

### ISSUE THREAD

**Issue by dohankk** [metaplex-foundation/js#528]
On devnet, the name is changed to `Unrecognized Token` after burning.
but not on mainnet.

Is it possible to change the name as above after burning in mainnet?

**Comment by lorisleiva** [comment]
Hi there, I'm not sure what you mean by that. Once burned the NFT or fungible token no longer has a Metadata account and therefore it won't have a name anymore. This issue may be with whichever explorer you are using and it may be that, on mainnet, they use an indexer that takes a while to update the info.

**Comment by dohankk** [comment]
Thanks :)
