### ISSUE TITLE
[feat]: fetching all minted NFTs from a Candy Machine

### ISSUE THREAD

**Issue by thlorenz** [metaplex-foundation/js#53]

**Comment by laurensV** [comment]
Don't we already have this feature with the function `metaplex.nfts().findAllByCandyMachine`?

**Comment by lorisleiva** [comment]
I added it there until we had the candy machine module basically.

But ideally, we should keep `nfts().findAllByCreator(...)` and move `nfts().findAllByCandyMachine(...)` to the candy machine module as something like `candyMachines().findAllMintedNfts(...)`.

**Comment by lorisleiva** [comment]
This method has been moved to the candy machine module as described above.
