### ISSUE TITLE
@metaplex-foundation/js not found

### ISSUE THREAD

**Issue by Lawrenxz** [metaplex-foundation/js#530]

**Comment by lorisleiva** [comment]
Please provide a detailed description of your issue.

**Comment by Lawrenxz** [comment]
> Please provide a detailed description of your issue.

I searched the same issue, they  downgrade the version of Metaplex and it works. I think I saw 0.12 something version.

**Comment by lorisleiva** [comment]
I mean, you should be able to download the latest version of the package. There were 9000 downloads for the very latest patch this week.

<img width="810" alt="CleanShot 2023-08-25 at 14 08 52@2x" src="https://github.com/metaplex-foundation/js/assets/3642397/b36d4923-1c16-46a7-88d4-167e61db0ebd">

**Comment by Lawrenxz** [comment]
yes I started on Latest version, here's the result 
![image](https://github.com/metaplex-foundation/js/assets/100080440/bd04b3e0-50fe-470b-9efb-01dbf4ded50b)

**Comment by lorisleiva** [comment]
What module resolution are you using for TS?

**Comment by Lawrenxz** [comment]
> What module resolution are you using for TS?

import {
  Metaplex,
  bundlrStorage,
  keypairIdentity,
} from "@metaplex-foundation/js"; like this?

**Comment by lorisleiva** [comment]
No I meant in your `tsconfig.json` file.

**Comment by Lawrenxz** [comment]
> No I meant in your `tsconfig.json` file.

![image](https://github.com/metaplex-foundation/js/assets/100080440/190d5f43-fa9d-48b4-b877-1d96736b8a52)

**Comment by lorisleiva** [comment]
Yeah I think that could be the issue. If you use a different `moduleResolution` it should recognise the type definitions. There are a few tweak that TS libraries need to do to export these types to newer module resolutions that I've not done on that library.

**Comment by Lawrenxz** [comment]
Got it. I will search it. Thank you sir.
