### ISSUE TITLE
Issue with bundlrStorage Import in Solana Bootcamp Quest-1, Script 6

### ISSUE THREAD

**Issue by Csonuzun** [metaplex-foundation/js#538]
# Issue: ImportError in createNFTs.ts using Metaplex Foundation JS

## Description
While working on the Solana Bootcamp Quest-1, Script 6 (`createNFTs.ts`), I encountered an import error with the `@metaplex-foundation/js` package. After uninstalling and reinstalling `metaplex-foundation.js`, the issue persists.

## Environment
- **Operating System:** macOS Sonoma 14.0 (23A344)
- **Node Version:** v20.4.0
- **Solana CLI Version:** solana-cli 1.17.6 (src:61caae6b; feat:3073089885, client:SolanaLabs)

## Error Details
The error occurs when attempting to import `bundlrStorage` from `@metaplex-foundation/js`. The specific line of code causing the issue is:

```typescript
import { Metaplex, bundlrStorage, keypairIdentity } from "@metaplex-foundation/js";
```

The error message received is:

```
Module '"@metaplex-foundation/js"' has no exported member 'bundlrStorage'.
```

## Steps to Reproduce
1. Uninstall and reinstall `metaplex-foundation.js`.
2. Run the `createNFTs.ts` script as part of the Solana Bootcamp Quest-1.

## Expected Behavior
The script should import the necessary modules from `@metaplex-foundation/js` without any import errors.

## Actual Behavior
An import error is thrown, indicating that `bundlrStorage` is not an exported member of `@metaplex-foundation/js`.

## Additional Information
Any additional guidance or suggestions for resolving this import error would be greatly appreciated.

**Comment by lorisleiva** [comment]
It has been replaced by the latest Bundlr client:

https://github.com/metaplex-foundation/js/pull/533
