### ISSUE TITLE
(0 , codecs_1.getBytesCodec) is not a function

### ISSUE THREAD

**Issue by Ibby-debug** [metaplex-foundation/js#551]
Anyone get this error ? I can't wrap my head around this issue.

**Comment by MohsinAliSoomro** [comment]
I am getting this error, @metaplex-foundation/js (0 , codecs_1.getBytesCodec) is not a function

**Comment by Ibby-debug** [comment]
Yeah it appears to be a circular dependency issue, I recommend you double check your react app setup. Here are also some working versions of this https://github.com/metaplex-foundation/js-examples
